# Generated by Django 5.2.15 on 2026-09-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('requires_schedule', models.BooleanField(default=False, help_text='Reserved for roadmap 2.5B -- will require an active scheduled talent assignment in addition to Role membership once TalentAssignment exists. Not yet enforced by anything in 2.5A.')),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='role_binding', to='auth.group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_bindings', to='authz.role')),
            ],
            options={
                'verbose_name': 'Group Role',
                'verbose_name_plural': 'Group Roles',
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_roles', to='authz.capability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='authz.role')),
            ],
            options={
                'verbose_name': 'Role Capability',
                'verbose_name_plural': 'Role Capabilities',
                'unique_together': {('role', 'capability')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='capabilities',
            field=models.ManyToManyField(related_name='roles', through='authz.RoleCapability', to='authz.capability'),
        ),
    ]
