# Generated by Django 5.2.15 on 2026-09-27 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_seed_capabilities_and_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_schedule_allowance_minutes', models.PositiveIntegerField(default=10, help_text="How many minutes before an assignment's scheduled start its schedule-restricted capabilities become usable. 0 is valid (no early access).")),
                ('post_schedule_allowance_minutes', models.PositiveIntegerField(default=15, help_text="How many minutes after an assignment's scheduled end its schedule-restricted capabilities remain usable. 0 is valid (access ends exactly at the scheduled end time).")),
            ],
            options={
                'verbose_name': 'Schedule Access Config',
                'verbose_name_plural': 'Schedule Access Config',
            },
        ),
        migrations.CreateModel(
            name='TalentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(help_text='If this is less than or equal to Start time, the assignment is interpreted as crossing midnight (e.g. 22:00 -> 02:00 means through 2 AM the following day).')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to disable this assignment without deleting it (e.g. a host on hiatus). An inactive assignment never satisfies a scheduled capability check.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Talent Assignment',
                'verbose_name_plural': 'Talent Assignments',
                'ordering': ['user__username', 'specific_date', 'day_of_week', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('day_of_week__isnull', False), ('specific_date__isnull', True)), models.Q(('day_of_week__isnull', True), ('specific_date__isnull', False)), _connector='OR'), name='talentassignment_exactly_one_of_day_or_date')],
            },
        ),
    ]
