# Generated by Django 5.2.15 on 2026-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0004_seed_schedule_access_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleaccessconfig',
            name='scheduled_enforcement_enabled',
            field=models.BooleanField(default=False, help_text='Roadmap 2.5C activation switch. OFF (the default, including on every existing/upgraded installation): schedule-restricted capabilities behave as ordinary capabilities -- the account must still hold the capability, but no TalentAssignment is required. ON: the account must ALSO have an active TalentAssignment whose effective window covers the current moment. This never affects ordinary (non-scheduled) capabilities. The admin form refuses to turn this ON while an active, non-staff account holds a schedule-restricted capability but has zero Talent Assignment rows configured at all -- see docs/AUTHORIZATION.md\'s "Safe activation" section.'),
        ),
    ]
