"""KanDrive audio synthesis and Track lifecycle.

Output-unit design (see report.py's module docstring for the length
reasoning that follows from it): KanDrive is ONE consolidated,
in-place-updated report -- a single stable file/Track, filepath-keyed,
regenerated in full on every successful cycle -- rather than one file
per event or a bounded set of "parts." This mirrors weather's own
WxForecast/WxObs/WxTemp family exactly (see the migration comment in
library/migrations/0076_add_kandrive_category.py): each of those is
also a single reused Track a human has manually wired into rotation,
regenerated by filepath-keyed update_or_create on its own schedule,
never accumulating. It deliberately does NOT follow the Dedications
family's pattern (one file per SongRequest id, urgent-splice-only,
zero RotationSlots) -- KanDrive IS meant to be rotation-eligible (the
operator adds it to rotations manually, per the task's own
instructions), so unlike a dedication intro it needs REAL crossfade
cue points, not the speech-clip opt-out next_start_seconds=duration
trick dedication intros use. That's why this module calls
analyze_one_track(force=True) and, unlike synthesize_dedication_intro,
never re-asserts next_start_seconds/cue_in_seconds afterward -- the
real envelope-based analysis is exactly what this Track needs to
crossfade correctly against whatever plays before/after it in a
rotation, the same as any other rotation category.

Rejected alternative -- one file per event: would multiply Track/file
count without bound as events churn, and the task explicitly prefers
"a small, predictable set of current KanDrive audio assets rather than
an ever-growing archive."

Rejected alternative -- bounded parts (e.g. Part 1/Part 2): would
require the rotation to play them in a specific order to remain
comprehensible, but RotationSlot.rotation_weight's own docstring
states selection is "not a guarantee" -- rotation is random-weighted,
not sequence-preserving. A multi-part report could play Part 2 without
Part 1 ever having aired, or hours apart, which would be actively
confusing rather than helpful. Not adopted.

Kokoro invocation mirrors the established in-Django pattern
(webrequests/services.py's synthesize_dedication_intro) exactly: same
binary, same WAV-then-ffmpeg-to-FLAC pipeline, same atomic
os.replace() (the final path is never touched until the new file is
completely written and its duration probed), same temp-file naming and
cleanup. A failure at any point in synthesis leaves the existing
final_path (and its Track row) completely untouched -- the last
known-good report keeps airing rather than going silent or corrupt.

Loudness normalization: the final spoken audio (whether one Kokoro
call or several spliced with a transition sound -- see
_synthesize_with_transitions()) is run through the SAME two-pass EBU
R128 loudnorm target the KNS show ingest script applies to every other
syndicated show (get_kns.py's own LOUDNORM_TARGETS/build_loudnorm_
string/two-pass analyze-then-encode structure, duplicated here rather
than cross-imported). True
two-pass loudnorm structurally can't run as a single streaming pass
over a pipe -- the second pass's linear correction needs the first
pass's COMPLETE measurement before it can correctly apply anything
starting from sample 0 -- so this needs a real, re-readable file for
Kokoro's raw output (and, on the transition-sound path, each segment's
own WAV). Kokoro's own writer (see kokoro_synth's _kokoro_synth.py)
uses Python's `wave` module, which seeks back to patch the RIFF header
on close and so also can't write to a pipe/stdout regardless. Given
both constraints, the closest thing to "no disk I/O for this scratch
audio" is a tmpfs (RAM-backed, not real disk) directory -- see
TMP_AUDIO_ROOT below -- rather than true zero-file streaming, which
isn't possible here. The FINAL FLAC still lands on real disk at
KANDRIVE_ROOT, same as always; only the throwaway intermediate audio
moves to tmpfs, and every temp file (there or at KANDRIVE_ROOT) is
unlinked in synthesize_road_report()'s own `finally` block once the
final file has been written (or on failure) -- see that function.
"""
import hashlib
import os
import re
import subprocess
from pathlib import Path

from django.conf import settings
from django.db import transaction

from isadoraair.tts.errors import TTSError
from isadoraair.tts.station import synthesize_station_voice
from library.models import AnalysisConfig, Category, Track

KANDRIVE_ROOT = Path(settings.LIBRARY_ROOT) / "KanDrive"
KANDRIVE_FILENAME = "road_report.flac"

# Scratch directory for Kokoro's own raw WAV output (and, on the
# transition-sound path, each segment's WAV) -- /dev/shm is a real,
# POSIX-standard tmpfs (RAM-backed, not the real disk KANDRIVE_ROOT
# lives on) on this box, verified via `mount` (tmpfs on /dev/shm).
# Kept as its own subdirectory (not written directly into /dev/shm's
# own root, which is world-writable/shared) purely for tidiness --
# nothing here is sensitive. See the module docstring above for why
# this can't just be an in-process pipe instead.
TMP_AUDIO_ROOT = Path("/dev/shm/isadoraair-kandrive")

# The exact same EBU R128 targets the KNS show ingest script applies
# to every other syndicated show (get_kns.py's own LOUDNORM_TARGETS) --
# so KanDrive's spoken reports sit at the same on-air loudness as
# everything else, not a KanDrive-specific guess.
LOUDNORM_TARGETS = {"I": -16.0, "TP": -1.0, "LRA": 5.0}

# A separate counter from report.REPORT_FINGERPRINT_VERSION (see that
# module's compute_report_fingerprint()) -- this one versions the
# actual AUDIO ENCODING pipeline (loudnorm targets, sample format/rate,
# FLAC compression settings, the Kokoro invocation shape itself), not
# the fingerprint payload's own schema. Bump this alone when a change
# here would produce materially different audio bytes for byte-
# identical `text`/voice/transition inputs (e.g. changing
# LOUDNORM_TARGETS, or the ffmpeg filter chain) -- that forces every
# existing "unchanged" report to regenerate on its next cycle without
# also needing to touch report.py's fingerprint schema. Never derived
# from a git commit or timestamp -- a plain, deliberately-incremented
# integer, same spirit as REPORT_FINGERPRINT_VERSION.
AUDIO_FORMAT_VERSION = 1

# Companion audit/debug text file -- see write_road_report_text()'s own
# docstring for exactly when this is (and isn't) updated.
KANDRIVE_TEXT_FILENAME = "road_report.txt"

# "Oak Grove Radio" -- the exact artist string already used on every
# other spoken-segment Track this project generates (WxForecast,
# WxObs, WxTemp; verified live via the database). Reused, not
# reinvented, for the same reason road_conditions/voice.py reuses
# weather's own voice identities rather than picking new ones.
KANDRIVE_ARTIST_NAME = "Oak Grove Radio"


class SynthesisError(Exception):
    """Raised when Kokoro/ffmpeg/duration-probing fails. The caller
    (the management command) decides how to log/report this; this
    module never leaves a partial file at final_path either way."""


def road_report_path():
    """Public accessor for the single, stable KanDrive output path --
    callers (the management command's preview output) use this rather
    than reconstructing KANDRIVE_ROOT / KANDRIVE_FILENAME themselves."""
    return KANDRIVE_ROOT / KANDRIVE_FILENAME


def _final_path():
    return road_report_path()


def road_report_text_path():
    """Public accessor for the companion audit/debug text file, sitting
    alongside road_report_path()'s own FLAC -- same KANDRIVE_ROOT."""
    return KANDRIVE_ROOT / KANDRIVE_TEXT_FILENAME


def write_road_report_text(text):
    """Atomically updates road_report.txt to contain the exact final
    script -- an audit/debug copy of exactly what the system last
    generated for air, kept alongside road_report.flac. Same tmp-file +
    os.replace() atomic pattern already used for the FLAC itself (and
    webrequests/services.py's synthesize_dedication_intro before that):
    no reader ever observes a partially-written file, and a failure
    here (e.g. a full disk) leaves whatever text file already existed
    completely untouched -- it is never truncated or opened for
    in-place writing.

    NOT called from anywhere inside this module -- the caller
    (generate_road_condition_audio.py's _run()) calls this only AFTER
    synthesize_road_report() has returned successfully (FLAC written,
    Track row created/updated, AND waveform analysis has succeeded),
    so road_report.txt only ever comes to describe a generation cycle
    that completed successfully start to finish -- never a FLAC that
    was written but then the cycle went on to fail at the Track DB
    write or analysis step. See that command's own comment at the call
    site. Never called at all from a --dry-run, --text-only, or
    --event-id path, nor from the stale/failed/disabled retirement
    path -- those never reach a successful synthesize_road_report()
    call in the first place."""
    KANDRIVE_ROOT.mkdir(parents=True, exist_ok=True)
    final_text_path = road_report_text_path()
    pid = os.getpid()
    tmp_text = KANDRIVE_ROOT / f".{KANDRIVE_TEXT_FILENAME}.{pid}.tmp.txt"
    try:
        tmp_text.write_text(text, encoding="utf-8")
        os.replace(tmp_text, final_text_path)
    finally:
        try:
            tmp_text.unlink()
        except FileNotFoundError:
            pass


def hash_file_sha256(path):
    """SHA-256 hex digest of a file's exact bytes -- used by report
    fingerprinting (see report.compute_report_fingerprint()) to detect
    an in-place content change to the configured transition-sound file
    even though its pathname hasn't changed (a bare pathname string
    would miss that entirely). The transition sound is a short chime/
    sting, not a full track, so hashing it fresh on every generation
    cycle this feature is active is cheap -- no mtime/size caching,
    which would be one more thing that could silently drift from the
    file's real content."""
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def existing_report_is_healthy(expected_text):
    """True only if EVERY on-air artifact the current KanDrive report
    depends on is present and consistent with a generation cycle that
    already completed successfully:

      * road_report.flac exists on disk;
      * its corresponding KanDrive Track row exists;
      * that Track is ready2air=True (not pulled out of rotation by
        retire_road_report() during a stale/failed/disabled cycle);
      * road_report.txt exists and is readable;
      * road_report.txt's content exactly equals `expected_text` --
        the CURRENT cycle's own final composed script, not merely
        "some text file exists".

    Used ONLY alongside a fingerprint match (RoadConditionsConfiguration.
    last_report_fingerprint) when deciding whether generate_road_
    condition_audio can skip synthesis for an unchanged report -- see
    that command's own skip decision. A matching fingerprint by itself
    says "the INPUTS are unchanged since the last successful cycle";
    this says "the OUTPUT of that cycle is still actually in place and
    healthy". Both must be true to skip -- this is what correctly
    forces regeneration after e.g. a stale-feed retirement flips
    ready2air to False even though the underlying report content
    (and therefore its fingerprint) never changed.

    Deliberately does NOT attempt to repair any unhealthy condition it
    finds (e.g. flipping ready2air back on, or rewriting a missing
    text file) -- regeneration through the normal synthesis pipeline
    is the conservative, already-established behavior for a report
    artifact that isn't verifiably healthy; silently patching DB/file
    state here would risk marking something ready2air/current that
    was never actually verified end-to-end this cycle."""
    final_path = road_report_path()
    if not final_path.exists():
        return False
    track = Track.objects.filter(filepath=str(final_path)).first()
    if track is None or not track.ready2air:
        return False
    text_path = road_report_text_path()
    if not text_path.exists():
        return False
    try:
        existing_text = text_path.read_text(encoding="utf-8")
    except OSError:
        return False
    return existing_text == expected_text


def _probe_duration(path):
    """Same ffprobe pattern as webrequests/services.py's own
    _probe_duration (itself matching prep_mitd_show.py's) -- duration
    in seconds as a float."""
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nw=1:nk=1", str(path)],
        check=True, capture_output=True, text=True, timeout=15,
    )
    return float(out.stdout.strip())


def build_loudnorm_string(extra_args=""):
    """Same construction as the KNS show ingest script's own
    build_loudnorm_string() (get_kns.py) -- duplicated here rather
    than cross-imported. Uses LOUDNORM_TARGETS, the same numbers KNS
    applies to every other syndicated show."""
    base = "loudnorm=I={I}:TP={TP}:LRA={LRA}".format(**LOUDNORM_TARGETS)
    return f"{base}:{extra_args}" if extra_args else base


def _parse_loudnorm_output(ffmpeg_output_text):
    """Same regex-based parse as get_kns.py's own
    _parse_loudnorm_output -- loudnorm's analysis pass prints its
    measurements as JSON to stderr (via av_log at AV_LOG_INFO); this
    pulls out the five fields the encode pass needs, falling back to a
    looser numeric regex if the quoted-JSON form isn't found (matches
    the original)."""
    keys = ["input_i", "input_tp", "input_lra", "input_thresh", "target_offset"]
    analysis = {}
    for k in keys:
        m = re.search(rf'"{k}"\s*:\s*"([^"]+)"', ffmpeg_output_text)
        if m:
            analysis[k] = m.group(1)
        else:
            lm = re.search(rf'{k}[^-\d]*([-\d.]+)', ffmpeg_output_text, re.I)
            if lm:
                analysis[k] = lm.group(1)
    return analysis


def _run_loudnorm_two_pass(build_filter_args, tmp_flac):
    """Two-pass EBU R128 loudnorm, matching the KNS show ingest
    script's own analyze-then-encode structure exactly (get_kns.py's
    merge_audio_files): pass 1 measures the COMPLETE finished audio
    (whatever filter graph `build_filter_args` produces, with loudnorm
    applied as `print_format=json`, discarded via `-f null -`); pass 2
    re-runs the SAME graph with `measured_*`/`linear=true`/
    `print_format=summary` and writes the real FLAC output. See this
    module's own docstring for why a single streaming pass can't do
    this (pass 2's linear correction needs pass 1's complete
    measurement before it can correctly apply anything from the very
    first sample).

    `build_filter_args(loudnorm_filter_str)` must return the full
    ffmpeg argv up to (but not including) the final output-format/path
    arguments -- called twice, once per pass, with a different
    loudnorm filter string each time, against the SAME already-
    synthesized input file(s) (no re-synthesis between passes).

    A failed/incomplete analysis pass (rare -- a very short or unusual
    clip) falls back to the same conservative defaults KNS itself uses
    (get_kns.py's own fallback) rather than failing the whole cycle
    over a measurement quirk -- matching KNS's own `check=False`
    treatment of its analysis pass. The ENCODE pass is not forgiving:
    its failure (CalledProcessError/TimeoutExpired) propagates
    normally to the caller's existing except clause, same as every
    other ffmpeg call in this module."""
    analyze_filter = build_loudnorm_string("print_format=json")
    try:
        proc1 = subprocess.run(
            build_filter_args(analyze_filter) + ["-f", "null", "-"],
            capture_output=True, text=True, timeout=60,
        )
        analysis = _parse_loudnorm_output((proc1.stdout or "") + (proc1.stderr or ""))
    except (subprocess.TimeoutExpired, OSError):
        analysis = {}

    if not analysis or len(analysis) < 5:
        analysis = dict(input_i="-20", input_tp="-2", input_lra="6", input_thresh="-30", target_offset="0")

    encode_filter = build_loudnorm_string(
        f"measured_I={analysis['input_i']}:measured_TP={analysis['input_tp']}:"
        f"measured_LRA={analysis['input_lra']}:measured_thresh={analysis['input_thresh']}:"
        f"offset={analysis['target_offset']}:linear=true:print_format=summary"
    )
    # Generous but bounded -- this is encoding already-synthesized
    # short WAVs, not a sized estimate.
    subprocess.run(
        build_filter_args(encode_filter) + [
            "-ar", "44100", "-ac", "2", "-c:a", "flac", "-sample_fmt", "s16",
            "-compression_level", "5", str(tmp_flac),
        ],
        check=True, timeout=120, capture_output=True,
    )


def _synthesize_segment_wav(voice, text, output_wav):
    """Applied identically to the plain single-call path
    (synthesize_road_report's own body) and every per-segment call in
    _synthesize_with_transitions() below. Routes through the shared
    isadoraair.tts.station.synthesize_station_voice() API, passing ONLY
    voice["logical_voice_name"] -- an operator-selected logical station
    voice name -- never voice["model"] (which holds the RESOLVED
    provider voice id, e.g. "af_jessica", kept only for report.
    compute_report_fingerprint()'s fingerprint authenticity; see
    voice.py's _resolve_shared_schedule_voice()). Timeout is
    voice["tts_timeout_seconds"] (RoadConditionsConfiguration.
    tts_timeout_seconds, applied per call -- i.e. per segment on the
    transition-sound path, matching that field's own documented
    intent).

    `voice` is always a road_conditions.voice.resolve_voice()-shaped
    dict -- that function raises VoiceResolutionError before returning
    anything else (the direct-Kokoro fallback this used to route to for
    a legacy/unshaped dict was retired in r0029; that runtime no longer
    exists).

    Raises isadoraair.tts.errors.TTSError, caught by
    synthesize_road_report()'s own wrapping try/except and turned into
    a SynthesisError, non-fatal and last-known-good-preserving."""
    synthesize_station_voice(
        text,
        voice=voice["logical_voice_name"],
        output_path=output_wav,
        timeout_seconds=voice["tts_timeout_seconds"],
    )


def _synthesize_with_transitions(segments, voice, transition_sound_path, tmp_flac, pid, cleanup_paths):
    """One Kokoro call per entry in `segments` (written to TMP_AUDIO_ROOT,
    not KANDRIVE_ROOT -- see the module docstring), concatenated via
    two-pass loudnorm (_run_loudnorm_two_pass above) with
    `transition_sound_path` spliced in strictly BETWEEN consecutive
    segments -- never before the first or after the last. Mirrors the
    KNS show ingest script's own woosh-between-stories concat
    (get_kns.py's _build_merge_ffmpeg_args/_canonical_input_chain) and
    its two-pass loudnorm, applied to the whole concatenated program
    (not each item individually) exactly as KNS applies it to its own
    bumper+stories+wooshes together. Writes directly to `tmp_flac`.
    Returns the resulting duration in seconds.

    Every per-segment WAV this creates is appended to `cleanup_paths`
    (the caller's own `finally` unlinks them all, success or failure) --
    this function itself never cleans up, matching the rest of
    synthesize_road_report()'s established pattern of one shared
    cleanup list/block rather than each step managing its own.

    Raises SynthesisError on any Kokoro/ffmpeg failure, same as the
    plain single-call path -- a bad transition-sound file (corrupt,
    wrong format) surfaces here as an ffmpeg failure, not silently
    skipped; only a MISSING file is treated as "feature not usable
    right now" (see generate_road_condition_audio.py's own check,
    which is what decides whether transition_sound_path is passed in
    as non-None at all)."""
    TMP_AUDIO_ROOT.mkdir(parents=True, exist_ok=True)
    segment_wavs = []
    for i, segment_text in enumerate(segments):
        seg_wav = TMP_AUDIO_ROOT / f".{KANDRIVE_FILENAME}.{pid}.seg{i}.tmp.wav"
        cleanup_paths.append(seg_wav)
        _synthesize_segment_wav(voice, segment_text, seg_wav)
        segment_wavs.append(seg_wav)

    def build_filter_args(loudnorm_filter_str):
        inputs, parts, concat_labels = [], [], []
        idx = 0
        for i, seg_wav in enumerate(segment_wavs):
            inputs.extend(["-i", str(seg_wav)])
            parts.append(f"[{idx}:a]aresample=44100,aformat=sample_fmts=s16:channel_layouts=stereo[s{i}]")
            concat_labels.append(f"[s{i}]")
            idx += 1
            if i < len(segment_wavs) - 1:
                inputs.extend(["-i", str(transition_sound_path)])
                parts.append(f"[{idx}:a]aresample=44100,aformat=sample_fmts=s16:channel_layouts=stereo[w{i}]")
                concat_labels.append(f"[w{i}]")
                idx += 1
        segment_count = len(concat_labels)
        parts.append(f"{''.join(concat_labels)}concat=n={segment_count}:v=0:a=1,{loudnorm_filter_str}[final]")
        filter_complex = ";".join(parts)
        return (
            ["ffmpeg", "-hide_banner", "-loglevel", "warning", "-y"]
            + inputs
            + ["-filter_complex", filter_complex, "-map", "[final]"]
        )

    _run_loudnorm_two_pass(build_filter_args, tmp_flac)
    return _probe_duration(tmp_flac)


def synthesize_road_report(text, voice_slot, voice, segments=None, transition_sound_path=None):
    """Renders `text` through the shared TTS service via
    _synthesize_segment_wav() below, using the already-resolved
    `voice` dict (see road_conditions/voice.py's resolve_voice(), which
    is the ONLY place a voice should be chosen; this function just
    plays whatever it's handed) -- converts to FLAC, and attaches it as
    the single KanDrive Track via filepath-keyed update_or_create.

    `segments` and `transition_sound_path` are both optional and both
    default to None -- every existing caller passing just (text,
    voice_slot, voice) is completely unaffected and still gets the
    exact single-Kokoro-call behavior this function has always had.
    When BOTH are given, `segments` has 2+ entries, AND
    transition_sound_path is a real, existing file, this instead
    synthesizes each entry in `segments` as its OWN Kokoro call and
    concatenates them via ffmpeg with the transition sound file spliced
    in strictly BETWEEN consecutive segments -- see
    _synthesize_with_transitions() below, which mirrors the KNS show
    ingest script's own woosh-between-stories concat (get_kns.py's
    _build_merge_ffmpeg_args). `text` itself is not used for synthesis
    in that case (only `segments` is actually sent to Kokoro) -- it
    still identifies what the caller considers the human-readable full
    script (used for road_report.txt; see that call site), which by
    construction (report.py's compose_report_segments(), sharing
    _resolve_framing() with compose_report_script()) is exactly
    " ".join(segments).

    Any single segment with fewer than 2 real entries can't have a
    transition inserted anywhere (there's no boundary), so it silently
    falls back to the plain single-call path using `text` -- this is
    what makes a 0- or 1-event report, or the feature being disabled,
    behave identically to before this parameter existed.

    Raises SynthesisError on any Kokoro/ffmpeg/duration-probe failure
    -- the final path and any existing Track row are left completely
    untouched in that case (temp files are cleaned up regardless).
    Callers (the management command) decide how to log/report a
    SynthesisError; this function never silently swallows one, unlike
    synthesize_dedication_intro's own top-level catch-all -- KanDrive
    has no "next cycle will just retry automatically" scheduler of its
    own the way the dedication intro command's per-request loop does,
    so the command itself needs to see this failure to report it
    (Step 9's "individual event formatting failures... must not
    silently produce misleading audio" applies just as much to a
    synthesis-level failure).

    Does NOT itself write road_report.txt -- that's the caller's job
    (generate_road_condition_audio.py calls write_road_report_text(text)
    only after this function has returned successfully), so the
    companion text file only ever comes to describe a generation cycle
    that completed successfully start to finish, including waveform
    analysis -- not merely a FLAC that was written before a later
    Track/analysis failure. See write_road_report_text()'s own
    docstring.

    Returns the Track instance on success."""
    if voice.get("engine") != "kokoro":
        # Belt-and-suspenders -- road_conditions/voice.py's
        # resolve_voice() already refuses to return a non-Kokoro voice,
        # but this function is public and could in principle be called
        # directly (e.g. from a test) with a hand-built voice dict.
        raise SynthesisError(
            f"synthesize_road_report only supports the kokoro engine, got {voice.get('engine')!r}"
        )

    use_transitions = bool(segments) and len(segments) > 1 and bool(transition_sound_path)

    KANDRIVE_ROOT.mkdir(parents=True, exist_ok=True)
    final_path = _final_path()
    pid = os.getpid()
    tmp_flac = KANDRIVE_ROOT / f".{KANDRIVE_FILENAME}.{pid}.tmp.flac"
    # Every temp file this call creates (the plain path's one tmp_wav,
    # or the transition path's per-segment WAVs) is appended here so
    # the single `finally` below cleans up either way, success or
    # failure -- same "always attempt, ignore FileNotFoundError"
    # pattern already established for tmp_flac itself.
    cleanup_paths = [tmp_flac]

    try:
        try:
            if use_transitions:
                duration = _synthesize_with_transitions(
                    segments, voice, transition_sound_path, tmp_flac, pid, cleanup_paths,
                )
            else:
                TMP_AUDIO_ROOT.mkdir(parents=True, exist_ok=True)
                tmp_wav = TMP_AUDIO_ROOT / f".{KANDRIVE_FILENAME}.{pid}.tmp.wav"
                cleanup_paths.append(tmp_wav)
                # Timeout is voice["tts_timeout_seconds"] -- see
                # _synthesize_segment_wav() -- NOT copied from
                # webrequests/services.py's 30s -- that value is sized
                # for a several-second dedication intro. A KanDrive
                # report is a full multi-event round-up (~780 words /
                # ~5-6 minutes of speech on the live dataset at
                # reconnaissance time), so a report this length could
                # reasonably take several minutes of wall time to
                # synthesize. RoadConditionsConfiguration.
                # tts_timeout_seconds' own default (600s) gives real
                # headroom above that without being unbounded -- a
                # genuinely hung synthesis process still gets killed,
                # just not mistaken for one on a long report.
                _synthesize_segment_wav(voice, text, tmp_wav)

                def build_filter_args(loudnorm_filter_str):
                    filter_str = f"aresample=44100,aformat=sample_fmts=s16:channel_layouts=stereo,{loudnorm_filter_str}"
                    return ["ffmpeg", "-hide_banner", "-loglevel", "warning", "-y", "-i", str(tmp_wav), "-af", filter_str]

                _run_loudnorm_two_pass(build_filter_args, tmp_flac)
                duration = _probe_duration(tmp_flac)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, ValueError, TTSError) as exc:
            raise SynthesisError(f"Shared-TTS/ffmpeg synthesis failed: {exc}") from exc

        # Atomic -- no reader (the log builder, a manual admin listen,
        # a concurrent generation run) ever sees a partially-written
        # final_path. This is also the single point of no return: only
        # after this line has the last known-good report actually been
        # replaced.
        #
        # road_report.txt is deliberately NOT written here. An earlier
        # revision of this function wrote it immediately after this
        # os.replace() -- but that meant a LATER failure in this same
        # function (the Track DB write below, or waveform analysis)
        # would still raise SynthesisError while road_report.txt had
        # already been overwritten, leaving the text file describing a
        # generation cycle that never actually completed successfully.
        # write_road_report_text(text) is now called by the caller
        # (generate_road_condition_audio.py) ONLY after this whole
        # function returns a Track without raising -- see that
        # function's own docstring.
        os.replace(tmp_flac, final_path)
    finally:
        for p in cleanup_paths:
            try:
                p.unlink()
            except FileNotFoundError:
                pass

    with transaction.atomic():
        track, _created = Track.objects.update_or_create(
            filepath=str(final_path),
            defaults=dict(
                filename=final_path.name,
                format="flac",
                title=f"KanDrive Road Report ({voice['name']})",
                artist=_kandrive_artist(),
                duration_seconds=duration,
                category=_kandrive_category(),
                ready2air=True,
            ),
        )

    # Full, real analysis -- unlike the Dedications intro pattern, this
    # Track IS meant to crossfade normally in rotation, so it needs
    # actual envelope-based cue points, not a speech-clip opt-out. Not
    # wrapped in its own separate best-effort try/except the way
    # synthesize_dedication_intro's waveform step is: analyze_one_track
    # itself already tolerates unreadable/unusual audio gracefully (it
    # returns False rather than raising -- verified against its own
    # implementation), and a KanDrive Track with no analysis at all
    # would have no cue points for the log builder to use, which is a
    # real defect worth surfacing as a SynthesisError rather than
    # silently leaving a technically-ready2air track with wrong/absent
    # crossfade behavior.
    analyzed = _run_full_analysis(track)
    if not analyzed:
        raise SynthesisError(
            f"KanDrive Track {track.id} was created/updated but waveform analysis failed "
            f"-- check {final_path} is readable by ffmpeg."
        )

    return track


def _run_full_analysis(track):
    from library.management.commands.analyze_tracks import analyze_one_track, get_waveforms_dir

    cfg = AnalysisConfig.load()
    cfg_values = (
        cfg.analysis_sample_rate, cfg.analysis_window_seconds, cfg.waveform_points,
        cfg.next_start_threshold_db, cfg.cue_in_threshold_db, cfg.cue_in_min_seconds,
    )
    if track.category_id:
        category = Category.objects.only(
            "next_start_threshold_db_override", "cue_in_threshold_db_override"
        ).get(pk=track.category_id)
        from library.management.commands.analyze_tracks import apply_category_thresholds
        cfg_values = apply_category_thresholds(
            cfg_values,
            category.next_start_threshold_db_override,
            category.cue_in_threshold_db_override,
        )
    row = (
        track.id, track.filepath, track.filename, track.duration_seconds,
        track.title, track.artist.name if track.artist_id else "", "",
    )
    return analyze_one_track(row, cfg_values, get_waveforms_dir(), force=True)


def _kandrive_category():
    # Created idempotently by library/migrations/0076_add_kandrive_category.py
    # -- .get() (not get_or_create) is deliberate: if it's ever missing,
    # that's a real deployment problem (a migration didn't run) worth
    # raising loudly, not silently papering over by recreating it here
    # with possibly-different defaults.
    return Category.objects.get(code="KanDrive")


def _kandrive_artist():
    from library.models import Artist
    artist, _ = Artist.get_or_create_ci(KANDRIVE_ARTIST_NAME)
    return artist


def retire_road_report():
    """Pulls the existing KanDrive Track out of rotation eligibility
    (ready2air=False) WITHOUT touching the file or deleting the row --
    used when road_conditions.report.feed_freshness() is anything
    other than "fresh" (stale/failed/disabled): the currently-airing
    report describes conditions from source data that can no longer be
    trusted as current, so it must stop being presented as such (Step
    8's "must not leave a stale report rotation-eligible" /
    "must not announce -- or keep airing -- as current when data
    freshness is uncertain"). The file and Track row are left in place
    (not deleted) so a subsequent fresh generation can cleanly
    update_or_create the same row again -- and so an operator
    inspecting the library can see exactly what was last actually
    reported, and when.

    Idempotent: a no-op, returning False, if no KanDrive Track exists
    yet or it's already ready2air=False.

    Deliberately does NOT touch analysis fields (next_start_seconds,
    cue_in_seconds, waveform) -- those describe the AUDIO FILE, which
    hasn't changed; only its rotation eligibility has."""
    updated = Track.objects.filter(filepath=str(_final_path()), ready2air=True).update(ready2air=False)
    return updated > 0
