"""KanDrive audio synthesis and Track lifecycle.

Output-unit design (see report.py's module docstring for the length
reasoning that follows from it): KanDrive is ONE consolidated,
in-place-updated report -- a single stable file/Track, filepath-keyed,
regenerated in full on every successful cycle -- rather than one file
per event or a bounded set of "parts." This mirrors weather's own
WxForecast/WxObs/WxTemp family exactly (see the migration comment in
library/migrations/0076_add_kandrive_category.py): each of those is
also a single reused Track a human has manually wired into rotation,
regenerated by filepath-keyed update_or_create on its own schedule,
never accumulating. It deliberately does NOT follow the Dedications
family's pattern (one file per SongRequest id, urgent-splice-only,
zero RotationSlots) -- KanDrive IS meant to be rotation-eligible (the
operator adds it to rotations manually, per the task's own
instructions), so unlike a dedication intro it needs REAL crossfade
cue points, not the speech-clip opt-out next_start_seconds=duration
trick dedication intros use. That's why this module calls
analyze_one_track(force=True) and, unlike synthesize_dedication_intro,
never re-asserts next_start_seconds/cue_in_seconds afterward -- the
real envelope-based analysis is exactly what this Track needs to
crossfade correctly against whatever plays before/after it in a
rotation, the same as any other rotation category.

Rejected alternative -- one file per event: would multiply Track/file
count without bound as events churn, and the task explicitly prefers
"a small, predictable set of current KanDrive audio assets rather than
an ever-growing archive."

Rejected alternative -- bounded parts (e.g. Part 1/Part 2): would
require the rotation to play them in a specific order to remain
comprehensible, but RotationSlot.rotation_weight's own docstring
states selection is "not a guarantee" -- rotation is random-weighted,
not sequence-preserving. A multi-part report could play Part 2 without
Part 1 ever having aired, or hours apart, which would be actively
confusing rather than helpful. Not adopted.

Kokoro invocation mirrors the established in-Django pattern
(webrequests/services.py's synthesize_dedication_intro) exactly: same
binary, same WAV-then-ffmpeg-to-FLAC pipeline, same atomic
os.replace() (the final path is never touched until the new file is
completely written and its duration probed), same temp-file naming and
cleanup. A failure at any point in synthesis leaves the existing
final_path (and its Track row) completely untouched -- the last
known-good report keeps airing rather than going silent or corrupt.
"""
import os
import subprocess
from pathlib import Path

from django.conf import settings
from django.db import transaction

from library.models import AnalysisConfig, Category, Track

# Same literal binary path used both in weather-ingest's lib/voices.py
# (external project) and webrequests/services.py (in-Django) --
# duplicated here rather than imported cross-app, matching this
# codebase's own established idiom of each app owning its own copy of
# this one constant (see webrequests/services.py's own comment on the
# same duplication against weather-ingest).
KOKORO_BINARY = "/home/jreed/kokoro/bin/kokoro_synth"

KANDRIVE_ROOT = Path(settings.LIBRARY_ROOT) / "KanDrive"
KANDRIVE_FILENAME = "road_report.flac"

# "Oak Grove Radio" -- the exact artist string already used on every
# other spoken-segment Track this project generates (WxForecast,
# WxObs, WxTemp; verified live via the database). Reused, not
# reinvented, for the same reason road_conditions/voice.py reuses
# weather's own voice identities rather than picking new ones.
KANDRIVE_ARTIST_NAME = "Oak Grove Radio"


class SynthesisError(Exception):
    """Raised when Kokoro/ffmpeg/duration-probing fails. The caller
    (the management command) decides how to log/report this; this
    module never leaves a partial file at final_path either way."""


def road_report_path():
    """Public accessor for the single, stable KanDrive output path --
    callers (the management command's preview output) use this rather
    than reconstructing KANDRIVE_ROOT / KANDRIVE_FILENAME themselves."""
    return KANDRIVE_ROOT / KANDRIVE_FILENAME


def _final_path():
    return road_report_path()


def _probe_duration(path):
    """Same ffprobe pattern as webrequests/services.py's own
    _probe_duration (itself matching prep_mitd_show.py's) -- duration
    in seconds as a float."""
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=nw=1:nk=1", str(path)],
        check=True, capture_output=True, text=True, timeout=15,
    )
    return float(out.stdout.strip())


def synthesize_road_report(text, voice_slot, voice):
    """Renders `text` via Kokoro (using the already-resolved `voice`
    dict -- see road_conditions/voice.py's resolve_voice(), which is
    the ONLY place a voice should be chosen; this function just plays
    whatever it's handed), converts to FLAC, and attaches it as the
    single KanDrive Track via filepath-keyed update_or_create.

    Raises SynthesisError on any Kokoro/ffmpeg/duration-probe failure
    -- the final path and any existing Track row are left completely
    untouched in that case (temp files are cleaned up regardless).
    Callers (the management command) decide how to log/report a
    SynthesisError; this function never silently swallows one, unlike
    synthesize_dedication_intro's own top-level catch-all -- KanDrive
    has no "next cycle will just retry automatically" scheduler of its
    own the way the dedication intro command's per-request loop does,
    so the command itself needs to see this failure to report it
    (Step 9's "individual event formatting failures... must not
    silently produce misleading audio" applies just as much to a
    synthesis-level failure).

    Returns the Track instance on success."""
    if voice.get("engine") != "kokoro":
        # Belt-and-suspenders -- road_conditions/voice.py's
        # resolve_voice() already refuses to return a non-Kokoro voice,
        # but this function is public and could in principle be called
        # directly (e.g. from a test) with a hand-built voice dict.
        raise SynthesisError(
            f"synthesize_road_report only supports the kokoro engine, got {voice.get('engine')!r}"
        )

    KANDRIVE_ROOT.mkdir(parents=True, exist_ok=True)
    final_path = _final_path()
    pid = os.getpid()
    tmp_wav = KANDRIVE_ROOT / f".{KANDRIVE_FILENAME}.{pid}.tmp.wav"
    tmp_flac = KANDRIVE_ROOT / f".{KANDRIVE_FILENAME}.{pid}.tmp.flac"

    try:
        try:
            # Timeout, NOT copied from webrequests/services.py's 30s --
            # that value is sized for a several-second dedication intro.
            # A KanDrive report is a full multi-event round-up (~780
            # words / ~5-6 minutes of speech on the live dataset at
            # reconnaissance time); kokoro_synth's own header comment
            # documents ~1.5-2x realtime throughput on this hardware
            # (a 30s forecast takes ~15-20s wall time), so a report this
            # length could reasonably take several minutes of wall time
            # to synthesize. 600s gives real headroom above that without
            # being unbounded -- a genuinely hung Kokoro process still
            # gets killed, just not mistaken for one on a long report.
            subprocess.run(
                [KOKORO_BINARY, "--model", voice["model"], "--output_file", str(tmp_wav)],
                input=text.encode("utf-8"), check=True, timeout=600,
            )
            # WAV->FLAC conversion is comfortably faster than realtime;
            # 120s is generous headroom, not a sized estimate.
            subprocess.run(
                ["ffmpeg", "-y", "-i", str(tmp_wav), str(tmp_flac)],
                check=True, timeout=120, capture_output=True,
            )
            duration = _probe_duration(tmp_flac)
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, ValueError) as exc:
            raise SynthesisError(f"Kokoro/ffmpeg synthesis failed: {exc}") from exc

        # Atomic -- no reader (the log builder, a manual admin listen,
        # a concurrent generation run) ever sees a partially-written
        # final_path. This is also the single point of no return: only
        # after this line has the last known-good report actually been
        # replaced.
        os.replace(tmp_flac, final_path)
    finally:
        for p in (tmp_wav, tmp_flac):
            try:
                p.unlink()
            except FileNotFoundError:
                pass

    with transaction.atomic():
        track, _created = Track.objects.update_or_create(
            filepath=str(final_path),
            defaults=dict(
                filename=final_path.name,
                format="flac",
                title=f"KanDrive Road Report ({voice['name']})",
                artist=_kandrive_artist(),
                duration_seconds=duration,
                category=_kandrive_category(),
                ready2air=True,
            ),
        )

    # Full, real analysis -- unlike the Dedications intro pattern, this
    # Track IS meant to crossfade normally in rotation, so it needs
    # actual envelope-based cue points, not a speech-clip opt-out. Not
    # wrapped in its own separate best-effort try/except the way
    # synthesize_dedication_intro's waveform step is: analyze_one_track
    # itself already tolerates unreadable/unusual audio gracefully (it
    # returns False rather than raising -- verified against its own
    # implementation), and a KanDrive Track with no analysis at all
    # would have no cue points for the log builder to use, which is a
    # real defect worth surfacing as a SynthesisError rather than
    # silently leaving a technically-ready2air track with wrong/absent
    # crossfade behavior.
    analyzed = _run_full_analysis(track)
    if not analyzed:
        raise SynthesisError(
            f"KanDrive Track {track.id} was created/updated but waveform analysis failed "
            f"-- check {final_path} is readable by ffmpeg."
        )

    return track


def _run_full_analysis(track):
    from library.management.commands.analyze_tracks import analyze_one_track, get_waveforms_dir

    cfg = AnalysisConfig.load()
    cfg_values = (
        cfg.analysis_sample_rate, cfg.analysis_window_seconds, cfg.waveform_points,
        cfg.next_start_threshold_db, cfg.cue_in_threshold_db, cfg.cue_in_min_seconds,
    )
    if track.category_id:
        category = Category.objects.only(
            "next_start_threshold_db_override", "cue_in_threshold_db_override"
        ).get(pk=track.category_id)
        from library.management.commands.analyze_tracks import apply_category_thresholds
        cfg_values = apply_category_thresholds(
            cfg_values,
            category.next_start_threshold_db_override,
            category.cue_in_threshold_db_override,
        )
    row = (
        track.id, track.filepath, track.filename, track.duration_seconds,
        track.title, track.artist.name if track.artist_id else "", "",
    )
    return analyze_one_track(row, cfg_values, get_waveforms_dir(), force=True)


def _kandrive_category():
    # Created idempotently by library/migrations/0076_add_kandrive_category.py
    # -- .get() (not get_or_create) is deliberate: if it's ever missing,
    # that's a real deployment problem (a migration didn't run) worth
    # raising loudly, not silently papering over by recreating it here
    # with possibly-different defaults.
    return Category.objects.get(code="KanDrive")


def _kandrive_artist():
    from library.models import Artist
    artist, _ = Artist.get_or_create_ci(KANDRIVE_ARTIST_NAME)
    return artist


def retire_road_report():
    """Pulls the existing KanDrive Track out of rotation eligibility
    (ready2air=False) WITHOUT touching the file or deleting the row --
    used when road_conditions.report.feed_freshness() is anything
    other than "fresh" (stale/failed/disabled): the currently-airing
    report describes conditions from source data that can no longer be
    trusted as current, so it must stop being presented as such (Step
    8's "must not leave a stale report rotation-eligible" /
    "must not announce -- or keep airing -- as current when data
    freshness is uncertain"). The file and Track row are left in place
    (not deleted) so a subsequent fresh generation can cleanly
    update_or_create the same row again -- and so an operator
    inspecting the library can see exactly what was last actually
    reported, and when.

    Idempotent: a no-op, returning False, if no KanDrive Track exists
    yet or it's already ready2air=False.

    Deliberately does NOT touch analysis fields (next_start_seconds,
    cue_in_seconds, waveform) -- those describe the AUDIO FILE, which
    hasn't changed; only its rotation eligibility has."""
    updated = Track.objects.filter(filepath=str(_final_path()), ready2air=True).update(ready2air=False)
    return updated > 0
