# Generated by Django 5.2.15 on 2026-07-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('protocol', models.CharField(choices=[('icecast', 'Icecast'), ('shoutcast1', 'Shoutcast 1'), ('shoutcast2', 'Shoutcast 2')], default='icecast', max_length=12)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField(default=8000)),
                ('mount', models.CharField(blank=True, help_text='Required for Icecast/Shoutcast 2. Not used for Shoutcast 1.', max_length=128)),
                ('username', models.CharField(blank=True, default='source', help_text='Icecast source username. Not used for Shoutcast 1/2.', max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('format', models.CharField(choices=[('mp3', 'MP3'), ('aac', 'AAC'), ('vorbis', 'Ogg Vorbis')], default='mp3', max_length=10)),
                ('bitrate_kbps', models.PositiveIntegerField(choices=[(64, '64 kbps'), (96, '96 kbps'), (128, '128 kbps'), (160, '160 kbps'), (192, '192 kbps'), (224, '224 kbps'), (256, '256 kbps'), (320, '320 kbps')], default=128)),
                ('input_device', models.CharField(blank=True, help_text='ALSA capture device. Defaults to the StereoTool HD Output bridge.', max_length=100)),
                ('station_name', models.CharField(blank=True, max_length=255)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('public', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Encoder',
                'verbose_name_plural': 'Encoders',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
