# Generated by Django 5.2.15 on 2026-07-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoder',
            name='format',
            field=models.CharField(choices=[('mp3', 'MP3'), ('aac', 'AAC'), ('vorbis', 'Ogg Vorbis')], default='mp3', help_text="MP3/Ogg Vorbis stream via GStreamer (shout2send). AAC streams via ffmpeg instead — GStreamer's shout2send element has no AAC support at all (confirmed: its sink pad only declares MP3/Ogg/WebM caps). Icecast/Shoutcast 2 only, not Shoutcast 1.", max_length=10),
        ),
    ]
