# Generated by Django 5.2.15 on 2026-07-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoders', '0002_alter_encoder_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoder',
            name='format',
            field=models.CharField(choices=[('mp3', 'MP3'), ('aac', 'AAC'), ('vorbis', 'Ogg Vorbis')], default='mp3', help_text='Streamed via Liquidsoap. AAC is Icecast/Shoutcast 2 only, not Shoutcast 1 (the legacy ICY protocol never supported anything but MP3 in practice).', max_length=10),
        ),
    ]
