# Generated by Django 5.2.15 on 2026-07-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoders', '0003_alter_encoder_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encoder',
            name='mount',
            field=models.CharField(blank=True, help_text="Icecast: the real mount path, e.g. /stream. Shoutcast 2: the numeric Stream ID, entered the same way, e.g. /4 for stream 4 (parsed into Liquidsoap's icy_id). Not used for Shoutcast 1.", max_length=128),
        ),
    ]
