# Generated by Django 5.2.15 on 2026-08-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encoders', '0004_alter_encoder_mount'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoder',
            name='mp3_rate_mode',
            field=models.CharField(choices=[('auto', 'Auto (bitrate-based, current default behavior)'), ('cbr', 'Constant bitrate (CBR)'), ('abr', 'Average bitrate (ABR)')], default='auto', help_text='Auto preserves the existing behavior exactly: bitrates below 192 kbps use LAME ABR, 192 kbps and up use CBR. CBR/ABR force that choice regardless of bitrate. Some providers (e.g. Live365, Radio.co) require an effective CBR MP3 stream -- Auto at 192 kbps or higher already satisfies that without changing this field.', max_length=4),
        ),
        migrations.AddField(
            model_name='encoder',
            name='provider',
            field=models.CharField(choices=[('generic', 'Generic'), ('live365', 'Live365'), ('radio_co', 'Radio.co')], default='generic', help_text='Generic: manually configured Icecast/Shoutcast destination. Live365/Radio.co: provider presets layered on top of the same generic Icecast/Shoutcast transport -- selecting one narrows which protocol/format/MP3 rate-mode combinations are accepted and how destination health is verified, it does not add a new streaming protocol.', max_length=10),
        ),
    ]
