# Generated by Django 5.2.15 on 2026-07-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RBDSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='127.0.0.1', help_text="StereoTool's RDS server address. Defaults to localhost since StereoTool normally runs on this same box.", max_length=255)),
                ('port', models.PositiveIntegerField(default=1001, help_text="StereoTool's UECP/ASCII server port. This box's own StereoTool instance uses 1001 (StereoTool's own generic default is 4001).")),
                ('transport', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=3)),
                ('protocol', models.CharField(choices=[('uecp', 'UECP (binary)'), ('ascii', 'StereoTool ASCII')], default='uecp', help_text="UECP is the real binary protocol StereoTool's encoder expects in normal use. ASCII is StereoTool's own simplified text alternative -- note TA is not sent at all in ASCII mode (StereoTool's ASCII dialect has no TA command).", max_length=5)),
                ('uecp_site_address', models.PositiveSmallIntegerField(default=1, help_text='UECP 10-bit site address (0-1023). Only used in UECP mode.')),
                ('uecp_encoder_address', models.PositiveSmallIntegerField(default=0, help_text='UECP 6-bit encoder address (0-63). Only used in UECP mode.')),
                ('pi_code', models.CharField(blank=True, default='', help_text='1-4 hex digit Program Identification code, e.g. 1000. Raw hex entry only -- no callsign-to-PI calculator in this version.', max_length=4)),
                ('station_ps', models.CharField(blank=True, help_text="Static 8-character PS (Program Service name) shown when no dynamic PS frame is configured below, e.g. 'KOGR-LP '. Padded/truncated to 8 chars automatically at send time.", max_length=8)),
                ('pty', models.PositiveSmallIntegerField(choices=[(0, 'No program type'), (1, 'News'), (2, 'Information'), (3, 'Sports'), (4, 'Talk'), (5, 'Rock'), (6, 'Classic Rock'), (7, 'Adult Hits'), (8, 'Soft Rock'), (9, 'Top 40'), (10, 'Country'), (11, 'Oldies'), (12, 'Soft'), (13, 'Nostalgia'), (14, 'Jazz'), (15, 'Classical'), (16, 'Rhythm and Blues'), (17, 'Soft R&B'), (18, 'Language'), (19, 'Religious Music'), (20, 'Religious Talk'), (21, 'Personality'), (22, 'Public'), (23, 'College'), (24, 'Spanish Talk'), (25, 'Spanish Music'), (26, 'Hip Hop'), (27, 'Unassigned'), (28, 'Unassigned'), (29, 'Weather'), (30, 'Emergency Test'), (31, 'Emergency')], default=0, help_text='RBDS Program Type -- this is the US RBDS table, NOT the European RDS PTY table (different numbering).')),
                ('tp', models.BooleanField(default=False, verbose_name='Traffic Program')),
                ('ta', models.BooleanField(default=False, help_text="Not sent at all when Protocol is ASCII mode (StereoTool's ASCII dialect has no TA command) -- the value is kept regardless so switching back to UECP doesn't lose it.", verbose_name='Traffic Announcement')),
                ('ms', models.BooleanField(default=True, help_text='Checked = Music, unchecked = Speech.', verbose_name='Music/Speech')),
                ('di_dynamic_pty', models.BooleanField(default=False, verbose_name='DI: Dynamic PTY')),
                ('di_compressed', models.BooleanField(default=False, verbose_name='DI: Compressed')),
                ('di_artificial_head', models.BooleanField(default=False, verbose_name='DI: Artificial Head')),
                ('di_stereo', models.BooleanField(default=True, verbose_name='DI: Stereo')),
                ('af_frequencies_mhz', models.CharField(blank=True, help_text="Comma-separated alternate frequencies in MHz, e.g. '89.5, 91.3'. Valid range 87.6-107.9. Only used in UECP mode (ASCII has no AF command).", max_length=255)),
                ('now_playing_format', models.CharField(default='{artist} - {title}', help_text="Python str.format() template applied to now_playing.json's artist/title fields. If artist is empty (e.g. an alt_send_text override), just {title} is sent verbatim. Truncated to 64 chars (RadioText limit).", max_length=255)),
                ('use_rt_plus', models.BooleanField(default=True, help_text="Tags artist/title within the RT string using StereoTool's RT+ ASCII extension. Binary-UECP RT+ requires the ODA channel, out of scope for this version -- RT+ is only ever sent when Protocol is ASCII.", verbose_name='Send RT+ tagging (ASCII mode only)')),
            ],
            options={
                'verbose_name': 'RBDS Config',
                'verbose_name_plural': 'RBDS Config',
            },
        ),
        migrations.CreateModel(
            name='RBDSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal label only, not transmitted.', max_length=100)),
                ('source_type', models.CharField(choices=[('static', 'Static text'), ('file', 'Local file'), ('url', 'URL')], default='static', help_text="Where this message's text comes from.", max_length=6)),
                ('text', models.CharField(blank=True, help_text="RadioText sent verbatim (64-char limit). Used when Source Type is 'Static text'.", max_length=64)),
                ('file_path', models.CharField(blank=True, help_text="Local file path read fresh every Poll Interval below. Used when Source Type is 'Local file'. Content is trimmed and truncated to 64 chars.", max_length=500)),
                ('source_url', models.URLField(blank=True, help_text="URL fetched (HTTP GET) fresh every Poll Interval below. Used when Source Type is 'URL'. Response body is trimmed and truncated to 64 chars.")),
                ('poll_interval_seconds', models.PositiveIntegerField(default=30, help_text='How often to re-read the file / re-fetch the URL. Ignored (no effect) for Static text.')),
                ('rt_plus_delimiter', models.CharField(blank=True, help_text="If set (e.g. '|'), the text is split on its first occurrence into artist|title for RT+ tagging. Leave blank to send the whole text as plain RT with no RT+ tags -- appropriate for text that isn't artist/title-shaped (e.g. a weather string).", max_length=4)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('display_seconds', models.PositiveSmallIntegerField(default=10, help_text="How long this message stays on-air each time it's shown, before reverting to now-playing RT.")),
                ('start_date', models.DateField(blank=True, help_text='Leave blank for no start restriction -- active immediately.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for no end restriction -- active indefinitely.', null=True)),
            ],
            options={
                'verbose_name': 'RT Rotation Message',
                'verbose_name_plural': 'RT Rotation Messages',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RBDSPSFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Exactly what's transmitted as PS (padded/truncated to 8 chars).", max_length=8)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('hold_seconds', models.PositiveSmallIntegerField(default=8, help_text='How long this frame stays on-air before rotating to the next.')),
            ],
            options={
                'verbose_name': 'PS Rotation Frame',
                'verbose_name_plural': 'PS Rotation Frames',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
