# Generated by Django 5.2.15 on 2026-07-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdsconfig',
            name='send_ct',
            field=models.BooleanField(default=False, help_text="Sends the encoder's real-time clock (UECP MEC 0x0D) so receivers can auto-set their displayed clock. UECP mode only (no ASCII equivalent exists). Per spec the underlying fields are always UTC plus a separate local-offset field the receiver applies itself -- this is computed automatically from the server's configured timezone, not something to set here.", verbose_name='Send Clock Time (CT)'),
        ),
    ]
