# Generated by Django 5.2.15 on 2026-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0002_rbdsconfig_send_ct'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdsconfig',
            name='nowplaying_min_seconds',
            field=models.PositiveIntegerField(default=20, help_text='Now-playing is the default/continuous RT state -- RT Rotation Messages periodically interrupt it for their own Display Seconds, then control returns to now-playing. This is the floor on how long now-playing must show again before the next message is allowed to interrupt it. Not itself a rotation slot -- see the RT Rotation Messages page for the promo side of the rotation.'),
        ),
    ]
