# Generated by Django 5.2.15 on 2026-07-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0003_rbdsconfig_nowplaying_min_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbdsconfig',
            name='port',
            field=models.PositiveIntegerField(default=4001, help_text="StereoTool's UECP/ASCII server port. 4001 is StereoTool's own generic default, and what this box's own StereoTool instance actually listens on."),
        ),
    ]
