# Generated by Django 5.2.15 on 2026-07-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0004_alter_rbdsconfig_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbdsconfig',
            name='use_rt_plus',
            field=models.BooleanField(default=True, help_text='Tags the artist/title inside the RadioText string so RT+-capable receivers can display Artist and Title as separate fields (car head units, TEF6686-class radios, etc.) instead of as one scrolling line. Works on both protocols: over ASCII it rides in the RT+= command; over binary UECP it uses the same proprietary MEC 0x24 sequence RDS Magic 4 sends to StereoTool (reverse-engineered from a live capture, byte-for-byte match against RDS Magic 4\'s output). RT sources that don\'t have a clean artist/title split (weather, promos, station IDs) get a single "cover the whole RT" tag instead, so receivers won\'t apply the previous song\'s offsets on top of the new text. Turn off to send only plain RadioText.', verbose_name='Send RT+ tagging'),
        ),
    ]
