# Generated by Django 5.2.15 on 2026-07-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0005_alter_rbdsconfig_use_rt_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbdsmessage',
            name='rt_plus_delimiter',
            field=models.CharField(blank=True, help_text="Controls how this message's RT+ tags are shaped. If set (e.g. '|'), the text is split on its first occurrence into artist and title, and two RT+ tags (item.artist + item.title) are emitted at the corresponding character offsets -- same shape as a now-playing song. Leave blank to emit a single tag covering the whole text -- appropriate for weather, promos, station IDs, and any message that isn't artist/title-shaped. That single-tag path is what prevents receivers from applying the previous song's artist/title offsets on top of this message's text (which they will happily do if no tags are sent at all).", max_length=4),
        ),
    ]
