# Generated by Django 5.2.15 on 2026-07-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0006_alter_rbdsmessage_rt_plus_delimiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdsconfig',
            name='ecc',
            field=models.CharField(blank=True, default='A0', help_text="Two-hex-digit ECC transmitted in RDS group 1A variant 0 to fully qualify the PI's country. A0 for the USA (all NRSC-4-B / RBDS stations). Leave blank to omit -- receivers then fall back to the PI's leading nibble for country inference, which works for US stations because PI codes starting with 1..3 are unambiguously US, but doesn't help Euro-style receivers or diagnostic tools. UECP-only feature: StereoTool's ASCII dialect has no ECC command, so this field is silently ignored when Protocol is ASCII mode (the value is kept regardless so switching back to UECP doesn't lose it).", max_length=2, verbose_name='ECC (Extended Country Code)'),
        ),
    ]
