# Generated by Django 5.2.15 on 2026-08-04 14:00, hand-trimmed to only the
# language_code field -- the auto-generated version also swept in
# unrelated pre-existing model/migration drift on di_dynamic_pty and
# RBDSPSFrame.hold_seconds (help_text/verbose_name changes from an
# earlier session that never got their own migration), out of scope
# for this change.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0008_blank_af_frequencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdsconfig',
            name='language_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Disabled / not transmitted'), (0, 'Unknown'), (1, 'Albanian'), (2, 'Breton'), (3, 'Catalan'), (4, 'Croatian'), (5, 'Welsh'), (6, 'Czech'), (7, 'Danish'), (8, 'German'), (9, 'English'), (10, 'Spanish'), (11, 'Esperanto'), (12, 'Estonian'), (13, 'Basque'), (14, 'Faroese'), (15, 'French'), (16, 'Frisian'), (17, 'Irish'), (18, 'Gaelic'), (19, 'Galician'), (20, 'Icelandic'), (21, 'Italian'), (22, 'Lappish'), (23, 'Latin'), (24, 'Latvian'), (25, 'Luxembourgian'), (26, 'Lithuanian'), (27, 'Hungarian'), (28, 'Maltese'), (29, 'Dutch'), (30, 'Norwegian'), (31, 'Occitan'), (32, 'Polish'), (33, 'Portuguese'), (34, 'Romanian'), (35, 'Romansh'), (36, 'Serbian'), (37, 'Slovak'), (38, 'Slovene'), (39, 'Finnish'), (40, 'Swedish'), (41, 'Turkish'), (42, 'Flemish'), (43, 'Walloon'), (64, 'Background'), (69, 'Zulu'), (70, 'Vietnamese'), (71, 'Uzbek'), (72, 'Urdu'), (73, 'Ukrainian'), (74, 'Thai'), (75, 'Telugu'), (76, 'Tatar'), (77, 'Tamil'), (78, 'Tadzhik'), (79, 'Swahili'), (80, 'SrananTongo'), (81, 'Somali'), (82, 'Sinhalese'), (83, 'Shona'), (84, 'Serbo-Croat'), (85, 'Ruthenian'), (86, 'Russian'), (87, 'Quechua'), (88, 'Pushtu'), (89, 'Punjabi'), (90, 'Persian'), (91, 'Papamiento'), (92, 'Oriya'), (93, 'Nepali'), (94, 'Ndebele'), (95, 'Marathi'), (96, 'Moldovian'), (97, 'Malaysian'), (98, 'Malagasay'), (99, 'Macedonian'), (100, 'Laotian'), (101, 'Korean'), (102, 'Khmer'), (103, 'Kazakh'), (104, 'Kannada'), (105, 'Japanese'), (106, 'Indonesian'), (107, 'Hindi'), (108, 'Hebrew'), (109, 'Hausa'), (110, 'Gurani'), (111, 'Gujurati'), (112, 'Greek'), (113, 'Georgian'), (114, 'Fulani'), (115, 'Dari'), (116, 'Churash'), (117, 'Chinese'), (118, 'Burmese'), (119, 'Bulgarian'), (120, 'Bengali'), (121, 'Belorussian'), (122, 'Bambora'), (123, 'Azerbaijan'), (124, 'Assamese'), (125, 'Armenian'), (126, 'Arabic'), (127, 'Amharic')], default=None, help_text="Optional legacy RDS Language Identification Code transmitted in group 1A through UECP. English is code 9. This is retained for receiver compatibility and is distinct from Long PS. Leave 'Disabled' to not send LIC at all -- this is the default so existing installations don't suddenly start transmitting it. UECP-only feature, same as ECC: silently ignored when Protocol is ASCII mode (the value is kept regardless).", null=True, verbose_name='Language (LIC)'),
        ),
    ]
