# Generated by Django 5.2.15 on 2026-08-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0009_rbdsconfig_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rbdsconfig',
            name='di_dynamic_pty',
            field=models.BooleanField(default=False, help_text='Tells receivers PTY may change from one track to the next. Automatically treated as True (regardless of this checkbox) whenever any Category has an RBDS PTY override configured at /admin/library/category/ -- PTY genuinely can vary in that case, so the indicator should say so. Enable manually here only to force it True with no category overrides configured.', verbose_name='DI: Dynamic PTY'),
        ),
        migrations.AlterField(
            model_name='rbdspsframe',
            name='hold_seconds',
            field=models.PositiveSmallIntegerField(default=8, help_text='How long this frame stays on-air before rotating to the next (minimum 4 seconds).'),
        ),
    ]
