# Generated by Django 5.2.15 on 2026-08-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0010_alter_rbdsconfig_di_dynamic_pty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdsconfig',
            name='dynamic_ps_frame_seconds',
            field=models.PositiveIntegerField(default=4, help_text='How long each generated frame stays on-air before advancing to the next. Modes 0 and 2 require at least 3 seconds per frame; Modes 1 and 3 (one-character scrolling) allow as little as 1 second.', verbose_name='Dynamic PS frame seconds'),
        ),
        migrations.AddField(
            model_name='rbdsconfig',
            name='dynamic_ps_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Mode 0 — Fixed 8-character cells (no scrolling)'), (1, 'Mode 1 — Scroll by 1 character'), (2, 'Mode 2 — Word-aligned scrolling'), (3, 'Mode 3 — Scroll by 1 character, blank spacing at start/end')], default=2, help_text='Which of the four frame-generation algorithms to apply to Dynamic PS Text. Only used when PS Mode is Generated Rotating PS. Default is Mode 2 (word-aligned).', verbose_name='Dynamic PS mode'),
        ),
        migrations.AddField(
            model_name='rbdsconfig',
            name='dynamic_ps_text',
            field=models.CharField(blank=True, default='', help_text='Operator-entered source text for Generated Rotating PS mode -- converted into a sequence of 8-character PS frames according to Dynamic PS Mode below (see rbds.services.dynamic_ps for the exact per-mode algorithm). May be left blank while PS Mode above is not Generated Rotating PS; must contain non-whitespace content when it is. Operator-entered text only in this version -- not sourced from now-playing/artist/title (RT/RT+ remain the authoritative current-title mechanism for that).', max_length=255, verbose_name='Dynamic PS text'),
        ),
        migrations.AddField(
            model_name='rbdsconfig',
            name='ps_mode',
            field=models.CharField(choices=[('static', 'Static PS'), ('manual', 'Manual PS Frames'), ('generated', 'Generated Rotating PS')], default='static', help_text='Controls only the ordinary 8-character PS service -- see the Program Service fieldset for the full explanation of each choice. Long PS (a separate, later RDS service) is not one of these values.', max_length=9, verbose_name='Short PS mode'),
        ),
        migrations.AlterField(
            model_name='rbdsconfig',
            name='station_ps',
            field=models.CharField(blank=True, help_text="Static 8-character PS (Program Service name), e.g. 'KOGR-LP '. Padded/truncated to 8 chars automatically at send time. Sent directly when PS Mode below is Static PS; also the fail-safe fallback for Manual PS Frames mode when zero frames are enabled.", max_length=8),
        ),
    ]
