# Generated by Django 5.2.15 on 2026-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0012_set_ps_mode_from_existing_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdsconfig',
            name='dynamic_ps_format',
            field=models.CharField(default='{text}', help_text="Template combining Dynamic PS Text with live now-playing information into the source string Dynamic PS Mode below actually generates frames from. Supported placeholders: {text} = Dynamic PS Text above; {now_playing} = current Artist - Title (just the title or artist alone if only one is known, blank if neither is -- the recommended token for a friendly, gap-free result); {artist} and {title} = the individual now-playing fields, blank when unknown, no special fallback handling (use {now_playing} instead if a clean fallback matters). Default '{text}' preserves the original, now-playing-free behavior exactly. Example: '{text} | Now Playing: {now_playing}'. Sourced ONLY from the currently-playing track -- never from RadioText, RT+ promos, weather, or any other RBDS message content, which continue rotating completely independently (see the RadioText fieldset below). No Python attribute/index access, conversion (!r), or format-spec (:...) syntax -- plain {field} placeholders only.", max_length=255, verbose_name='Dynamic PS format'),
        ),
        migrations.AlterField(
            model_name='rbdsconfig',
            name='dynamic_ps_text',
            field=models.CharField(blank=True, default='', help_text='Operator-entered source text for Generated Rotating PS mode -- combined with live now-playing information per Dynamic PS Format below (default: used verbatim, unchanged from pre-2.3E behavior), then converted into a sequence of 8-character PS frames according to Dynamic PS Mode below (see rbds.services.dynamic_ps for the exact per-mode algorithm). May be left blank while PS Mode above is not Generated Rotating PS; must contain non-whitespace content when it is -- this stays the safe branding/fallback source even for formats built mainly around now-playing.', max_length=255, verbose_name='Dynamic PS text'),
        ),
    ]
