# Generated by Django 5.2.15 on 2026-08-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbds', '0013_rbdsconfig_dynamic_ps_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rbdsconfig',
            name='long_ps_enabled',
            field=models.BooleanField(default=False, help_text='Transmits an extended, up to 32-character Program Service name alongside the ordinary 8-character PS above. Support varies by receiver. Only takes effect when Manage Long PS with IsadoraAir above is on.', verbose_name='Long PS enabled'),
        ),
        migrations.AddField(
            model_name='rbdsconfig',
            name='long_ps_managed',
            field=models.BooleanField(default=False, help_text='When off (the default), IsadoraAir sends no Long PS commands at all and leaves any existing encoder-local Long PS configuration untouched. Turn on to let IsadoraAir control Long PS using the settings below -- including explicitly turning Long PS off, if Long PS Enabled below is off.', verbose_name='Manage Long PS with IsadoraAir'),
        ),
        migrations.AddField(
            model_name='rbdsconfig',
            name='long_ps_source',
            field=models.CharField(choices=[('static', 'Static text'), ('now_playing', 'Now Playing')], default='static', help_text="Static text: always sends Long PS Static Text below. Now Playing: sends the current track's Artist - Title (just one field alone if only one is known), falling back to Long PS Static Text below whenever no usable now-playing metadata exists. Independent of PS Mode above -- any combination of the two is valid.", max_length=16, verbose_name='Long PS source'),
        ),
        migrations.AddField(
            model_name='rbdsconfig',
            name='long_ps_static_text',
            field=models.CharField(blank=True, default='', help_text='Up to 32 characters. Sent as-is when Long PS Source is Static text; also the fallback shown when Long PS Source is Now Playing but nothing usable is currently playing.', max_length=32, verbose_name='Long PS static text'),
        ),
    ]
