# Generated by Django 5.2.15 on 2026-08-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadConditionsConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Master switch. When off, sync_road_conditions fetches nothing and writes nothing -- everything else on this page is inert while off. Off by default so a fresh install doesn't start pulling KDOT data before the coverage filters are reviewed.")),
                ('api_base_url', models.URLField(default='https://kscars.kandrive.gov/carsapi_v1/api', help_text='CARS API root. The Kansas deployment is confirmed live at this URL as of 2026-08-04 (the ks.carsprogram.org console redirects here). Only change this if KDOT moves the endpoint.')),
                ('request_timeout_seconds', models.PositiveIntegerField(default=20, help_text='Read timeout in seconds for each CARS API request. A short, fixed 5-second connect timeout is always applied in code on top of this -- not admin-editable, since a slow DNS/TCP handshake should fail fast regardless of how patient the operator is willing to be for the response body itself.')),
                ('poll_cadence_minutes', models.PositiveIntegerField(default=15, help_text="How often sync_road_conditions actually runs -- ACTIVELY ENFORCED by the command itself (not just documentation): the systemd timer fires roughly every minute, and the command exits cleanly, writing nothing, whenever less than this many minutes have passed since the last attempt (see deploy/ for the proposed, not-yet-installed timer). A change here takes effect within about a minute, no timer edit or systemd reload needed -- same idiom as OGRemote's own poll_interval_minutes. 15 minutes by default: the live CARS API has no ETag/Last-Modified/conditional-request support and no pagination, so every poll re-downloads the COMPLETE current dataset (~8MB at reconnaissance time) -- at 5 minutes that's roughly 69GB/month; at 15 minutes roughly 23GB/month. This feed has no live crash/incident data (construction/closure/condition only -- see RoadEvent's docstring), so 15 minutes is a reasonable default; lower it (e.g. for winter road-condition operations) if that trade-off is worth it to you.")),
                ('event_classifications', models.CharField(default='constructionReports,roadReports,winterDriving,weatherWarningsAreaEvents', help_text="Comma-separated CARS API event classifications to request from the API's own eventClassifications query filter -- NOT the same thing as an individual event's headline_category/ headline_code (see RoadEvent). The live API recognizes exactly five values (confirmed via GET /eventClassifications): truckersReports, roadReports, winterDriving, weatherWarningsAreaEvents, constructionReports. There is no separate 'incidents' classification or crash/accident data in this feed at all -- KDOT's CARS API is construction/closure/condition-focused, not a crash feed.", max_length=200)),
                ('counties', models.CharField(blank=True, default='Ottawa,Saline,Cloud,Lincoln,Mitchell,Clay,Dickinson,Ellsworth', help_text="Comma-separated Kansas county names (as KDOT's API spells them, e.g. 'Ottawa', 'Saline' -- not FIPS codes) to keep. An event is kept if ANY of its counties match. Blank means no county filtering -- every event matching event_classifications above is kept, statewide.", max_length=500)),
                ('routes', models.CharField(blank=True, default='', help_text="Optional comma-separated exact route designators to further restrict to (applied client-side -- see note below). An event is kept if ANY of its locations' route matches ANY of these exactly. Verified live format: Kansas state highways are 'KS <number>' (e.g. 'KS 15', 'KS 18', 'KS 9') -- NOT 'K-15'/'K-18'/'K-9'. US/Interstate routes use 'US 81', 'I-70', 'US 24', etc. Blank means no route filtering. The API's own routeDesignator query param requires an exact full-string match with no OR support (confirmed live: 'US 81' returns real hits, the bare substring '81' returns none) -- so this is applied client-side against every route on a fetched event instead of sent to the API, which lets multiple routes be configured at once.", max_length=300)),
                ('min_priority', models.PositiveSmallIntegerField(default=1, help_text='Minimum CARS priority (1-10, as the API defines it) to keep. 1 keeps everything. Every live event has always carried a priority value in reconnaissance testing.')),
                ('max_event_age_days', models.PositiveIntegerField(default=3, help_text="Skip creating/updating a RoadEvent whose end-time (if the source provided one) is already more than this many days in the past. Defensive only -- the API describes /events as 'active and future' events, so this should rarely trigger; it guards against a stale end-time on an otherwise-still-listed record rather than being load-bearing for normal deactivation (that's source-presence-based -- see RoadEvent.source_active).")),
                ('lookahead_days', models.PositiveIntegerField(default=30, help_text="Skip creating/updating a RoadEvent whose start-time is more than this many days in the future. Keeps long-lead-time planned construction from filling the table months before it's ever relevant; raise it for earlier visibility into far-future projects.")),
                ('stale_data_threshold_minutes', models.PositiveIntegerField(default=30, help_text='If the last successful fetch is older than this many minutes, the admin shows a stale-data warning. Purely informational -- does not stop anything from running.')),
                ('debug_logging', models.BooleanField(default=False, help_text='Log full per-event sync decisions (kept/skipped/why) at INFO level. Off keeps routine polling quiet in the journal.')),
                ('last_fetch_attempted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_fetch_succeeded_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('last_record_count', models.PositiveIntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Road Conditions Configuration',
                'verbose_name_plural': 'Road Conditions Configuration',
            },
        ),
        migrations.CreateModel(
            name='RoadConditionsSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial (some records failed to parse)'), ('failed', 'Failed (could not complete the fetch)')], default='failed', max_length=16)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('relevant_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('unchanged_count', models.PositiveIntegerField(default=0)),
                ('deactivated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='CARS API fetch latency in milliseconds.', null=True)),
                ('error_message', models.TextField(blank=True, help_text="Set when outcome is 'failed' -- the exception/HTTP error that stopped the whole run.")),
            ],
            options={
                'verbose_name': 'Road Conditions Sync Run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text="The source 'event-id', e.g. 'CARS5-11556'. Stable across revisions (update-number increments; event-id does not change).", max_length=64, unique=True)),
                ('headline_category', models.CharField(blank=True, db_index=True, help_text="Source 'headline.category' -- this event's OWN taxonomy, e.g. 'roadwork', 'closure', 'restriction', 'warning', 'device-status', 'mobile-situation', 'special-event'. Distinct from RoadConditionsConfiguration.event_classifications, which is the API's separate QUERY-level filter (constructionReports/roadReports/etc.) -- do not confuse the two.", max_length=64)),
                ('headline_code', models.CharField(blank=True, help_text="Source 'headline.code' -- this event's own coded subtype, e.g. 'construction work', 'lane is closed', 'width restriction'.", max_length=128)),
                ('description', models.TextField(blank=True, help_text="Source top-level 'description' -- KDOT's own plain-English summary. The primary field for listener-facing text.")),
                ('priority', models.PositiveSmallIntegerField(blank=True, help_text="Source 'priority', 1 (low) - 10 (high) per the API's own schema.", null=True)),
                ('source_status', models.CharField(blank=True, help_text="Raw source 'status' string, e.g. 'UPDATED'. Observed constant across the live dataset -- NOT a reliable active/inactive signal; see `source_active` below.", max_length=32)),
                ('counties', models.JSONField(blank=True, default=list, help_text='Source "counties" array, e.g. ["Ottawa"]. Already complete -- never reduced to a single value.')),
                ('districts', models.JSONField(blank=True, default=list, help_text='Source "districts" array, e.g. ["DISTRICT 2"]. Already complete -- never reduced to a single value.')),
                ('primary_route', models.CharField(blank=True, db_index=True, help_text="Convenience field for admin display/sorting: the route from the FIRST detail location that has one, e.g. 'US 81', 'KS 15', 'I-70'. For a multi-route event, see `routes` below for the complete set -- this field alone does not represent the whole event.", max_length=128)),
                ('primary_direction', models.CharField(blank=True, help_text="Convenience field: the link-direction from that same first location, e.g. 'BOTH_DIRECTIONS', 'NORTHBOUND'. See `locations` below for the complete per-location detail.", max_length=32)),
                ('routes', models.JSONField(blank=True, default=list, help_text='Every distinct route designator across every detail location on this event (sorted), not just the first -- e.g. a two-segment event might list ["KS 4", "KS 140"]. Used for route-filtering (RoadConditionsConfiguration.routes) so a multi-segment event isn\'t missed just because its first location isn\'t the matching one.')),
                ('locations', models.JSONField(blank=True, default=list, help_text='Every distinct detail location on this event, normalized (location_type, route_designator, direction, latitude, longitude) -- preserves multi-location events completely; primary_route/primary_direction/latitude/longitude above are convenience copies of the first entry here, not a substitute for it.')),
                ('latitude', models.FloatField(blank=True, help_text='Convenience field: latitude of the first location with coordinates. See `locations` for the complete set.', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Convenience field: longitude of the first location with coordinates. See `locations` for the complete set.', null=True)),
                ('geometry', models.JSONField(blank=True, help_text="Raw source GeoJSON 'geometry' (Point or LineString in every live event seen) -- stored verbatim, never truncated (see raw_payload's sanitization note -- geometry is explicitly exempted from it).", null=True)),
                ('start_time', models.DateTimeField(blank=True, help_text='Earliest detail start-time, if the source provided one.', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Latest detail end-time, if the source provided one.', null=True)),
                ('source_update_time', models.DateTimeField(blank=True, help_text='Source top-level update-time -- when KDOT last revised this event.', null=True)),
                ('source_next_update_time', models.DateTimeField(blank=True, null=True)),
                ('source_update_expiry_time', models.DateTimeField(blank=True, help_text='Source update-expiry-time, stored as-is. Observed to sometimes be a generic far-future placeholder rather than a real expiry -- not used to drive deactivation.', null=True)),
                ('update_number', models.PositiveIntegerField(blank=True, help_text='Source revision counter -- increments on each KDOT edit, event-id stays the same.', null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(help_text="Updated every sync run where this event's id was present in a COMPLETE fetch (whether or not it parsed or matched current filters -- see services.sync_events).")),
                ('last_changed_at', models.DateTimeField(blank=True, help_text='Updated only when payload_checksum changed -- i.e. meaningful source content changed, not just re-seen unchanged or re-scoped.', null=True)),
                ('source_active', models.BooleanField(db_index=True, default=True, help_text="False once this event-id is absent from a COMPLETE, unnarrowed sync's fetch. Never flipped false after a failed/partial/narrowed sync -- see services.sync_events. Independent of `in_scope` -- see the model docstring.")),
                ('in_scope', models.BooleanField(db_index=True, default=True, help_text="True if this event currently matches RoadConditionsConfiguration's coverage filters (as of the last COMPLETE, unnarrowed sync). False if the operator's configured coverage changed and this event no longer matches -- independent of whether KDOT still lists it; see the model docstring.")),
                ('deactivated_at', models.DateTimeField(blank=True, help_text='When source_active last flipped to False. Unrelated to in_scope changes.', null=True)),
                ('raw_payload', models.JSONField(help_text="The source CARSEvent record, sanitized for storage: any list longer than services._MAX_LIST_ITEMS_IN_STORED_PAYLOAD is truncated (with a marker noting how many items were omitted) EXCEPT the top-level `geometry` object, which is always stored verbatim. This exists because a real live event (a K-15 closure) carried a 1,872-point turn-by-turn detour route under details[].descriptions[].locations-on-detour -- undocumented in the API's own Swagger spec, not mapped to any RoadEvent field, and ~890KB unsanitized for that one record alone. payload_checksum below is computed from the COMPLETE, unsanitized source record, before this truncation -- so a real content change inside a truncated array still changes the checksum and triggers an update, even though the stored copy here won't show the change.")),
                ('payload_checksum', models.CharField(db_index=True, help_text="sha256 of the canonicalized, UNSANITIZED raw source payload -- lets sync detect 'unchanged' without a deep field-by-field diff, and still detects changes inside content that gets truncated in the stored raw_payload above.", max_length=64)),
            ],
            options={
                'verbose_name': 'Road Event',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['source_active', 'in_scope', '-last_seen_at'], name='road_condit_source__366310_idx'), models.Index(fields=['headline_category', 'source_active'], name='road_condit_headlin_e5a1a5_idx')],
            },
        ),
    ]
