# Generated by Django 5.2.15 on 2026-08-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_conditions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadconditionsconfiguration',
            name='report_postamble',
            field=models.TextField(blank=True, default="For more information visit KanDrive dot gov. That's the Oak Grove Radio road report, I'm {announcer_name}.", help_text='Spoken immediately AFTER the generated road-condition report body (or the no-current-events message), every time. Optional -- blank means no postamble at all. Same {announcer_name} substitution support as report_preamble above.'),
        ),
        migrations.AddField(
            model_name='roadconditionsconfiguration',
            name='report_preamble',
            field=models.TextField(blank=True, default="Now here's the current and upcoming road report for the Oak Grove Radio listening area.", help_text='Spoken immediately BEFORE the generated road-condition report body (or the no-current-events message), every time. Optional -- blank means no preamble at all. May include the literal token {announcer_name}, replaced with the listener-facing name of whichever voice is currently selected for this report.'),
        ),
    ]
