# Generated by Django 5.2.15 on 2026-08-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_conditions', '0002_roadconditionsconfiguration_report_postamble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadconditionsconfiguration',
            name='report_preamble',
            field=models.TextField(blank=True, default="Now here's the current and upcoming road report for the Oak Grove Radio listening area.", help_text="Spoken immediately BEFORE the generated road-condition report body (or the no-current-events message), every time. Optional -- blank means no preamble at all. May include the literal token {announcer_name}, replaced with the full listener-facing name (e.g. 'Claira Sky') of whichever voice is currently selected for this report."),
        ),
    ]
