# Generated by Django 5.2.15 on 2026-08-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_conditions', '0004_roadconditionsconfiguration_transition_sound_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadconditionsconfiguration',
            name='transition_sound_enabled',
            field=models.BooleanField(default=False, help_text="Insert a short transition sound effect between individual road-condition items when the report speaks more than one. Off by default. Requires transition_sound_path below to point at a real, readable audio file at generation time; if it doesn't, the report is generated WITHOUT the transition sound rather than failing the whole cycle."),
        ),
        migrations.AlterField(
            model_name='roadconditionsconfiguration',
            name='transition_sound_path',
            field=models.CharField(blank=True, default='/home/jreed/syndicated-ingest/kns/woosh.wav', help_text='Absolute filesystem path to the transition sound effect audio file (e.g. a short chime or sting). Only read when transition_sound_enabled above is on. If this path is blank, missing, or unreadable at generation time, the report is generated without the transition sound (a warning is printed) rather than failing -- if the file itself is present but corrupt/unplayable, ffmpeg will fail and the whole generation cycle is reported as failed, same as any other synthesis error.', max_length=1024),
        ),
    ]
