# Generated by Django 5.2.15 on 2026-08-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_conditions', '0005_alter_roadconditionsconfiguration_transition_sound_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadconditionsconfiguration',
            name='additional_route_coverage',
            field=models.TextField(blank=True, default='', help_text="Optional exceptions to the Counties/Routes coverage above, one rule per line, in the form 'ROUTE: County,County' -- e.g. 'US 81: Saline,Cloud'. Counties above define the normal coverage area; Routes above, if also set, further RESTRICTS Counties (an event must match both). This field instead ADDS coverage: an event is also kept if it matches the exact route on a line here AND is in one of that line's listed counties -- regardless of whether it would otherwise pass Counties/Routes above. Each line only ever adds that one route in those exact counties, never statewide. Blank means no additional coverage (current behavior, unchanged). All other filters (event classifications, minimum priority, event age/lookahead) still apply normally to anything matched here -- this field only widens geographic scope, nothing else. Malformed lines (no ':', no route, or no counties listed) are rejected when this configuration is saved rather than silently broadening coverage. Known limitation: matching is EVENT-level, not per-segment -- the source API gives no route-to-county association for an event with more than one route (e.g. an event listing both US 81 and KS 9 with counties Ottawa and Cloud doesn't say which route is in which county), so a rule matches whenever its route and one of its counties both appear ANYWHERE on the event. Harmless for the vast majority of real events (each has exactly one route in practice; see services._matches_scope()'s docstring), but worth knowing for the rare event that genuinely spans multiple distinct routes."),
        ),
    ]
