# Generated by Django 5.2.15 on 2026-08-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_conditions', '0006_roadconditionsconfiguration_additional_route_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadconditionsconfiguration',
            name='last_report_fingerprint',
            field=models.CharField(blank=True, editable=False, help_text="SHA-256 hex digest of the effective on-air artifact from the last generate_road_condition_audio cycle that completed synthesis, FLAC installation, Track update, AND waveform analysis -- see report.py's compute_report_fingerprint(). Read-only. A later run compares its own freshly-computed fingerprint against this (plus a live health check on the existing FLAC/Track/text file) to decide whether the report is genuinely unchanged and synthesis can be skipped.", max_length=64),
        ),
        migrations.AddField(
            model_name='roadconditionsconfiguration',
            name='last_report_generated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='When last_report_fingerprint above was last set -- i.e. the last time generate_road_condition_audio actually completed a full synthesis cycle, not merely the last time the command RAN (a skipped-because-unchanged run, or --dry-run/--text-only/--event-id, never updates this).', null=True),
        ),
    ]
