# Generated by Django 5.2.15 on 2026-08-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_conditions', '0007_roadconditionsconfiguration_last_report_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadevent',
            name='cause_categories',
            field=models.JSONField(blank=True, default=list, help_text='Every distinct category from this event\'s own details[].descriptions[] entries marked is-cause=true (sorted), e.g. ["closure", "roadwork"] -- see services.extract_cause_categories(). Distinct from headline_category above: KDOT\'s own top-level headline is sometimes the EFFECT rather than the cause (confirmed on real live events: a headline of \'automated traffic signals\'/\'device-status\' with \'closure\'/\'roadwork\' recorded here as the real is-cause reason). report.py\'s select_events()/_severity_tier() use this so a genuine lane closure isn\'t dropped or under-prioritized just because of what KDOT chose as the record\'s top-level headline. Empty for the common case where the source provided no is-cause PhraseDescription entries (i.e. the top-level headline already IS the real reason).'),
        ),
    ]
