# Generated by Django 5.2.10 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("road_conditions", "0009_backfill_cause_categories"),
        ("tts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadconditionsconfiguration",
            name="tts_timeout_seconds",
            field=models.PositiveIntegerField(default=600, help_text="Future per-segment shared-TTS timeout for long road reports. This deliberately does not change the shared service's shorter generic default."),
        ),
        migrations.AddField(
            model_name="roadconditionsconfiguration",
            name="tts_use_weather_schedule",
            field=models.BooleanField(default=False, help_text="Future cutover option: resolve the current WeatherConfig schedule through Weather Voice Personas instead of using the fixed voice above. Off by default."),
        ),
        migrations.AddField(
            model_name="roadconditionsconfiguration",
            name="tts_voice",
            field=models.ForeignKey(blank=True, help_text="Logical voice reserved for the later shared-TTS road-report cutover. Blank keeps the current external weather-voice/Kokoro path unchanged.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="road_condition_configurations", to="tts.stationttsvoice"),
        ),
    ]
