# Generated by Django 5.2.15 on 2026-09-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_conditions', '0010_roadconditionsconfiguration_tts'),
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadconditionsconfiguration',
            name='tts_timeout_seconds',
            field=models.PositiveIntegerField(default=600, help_text="Per-segment shared-TTS timeout for long road reports. This deliberately does not change the shared service's shorter generic default."),
        ),
        migrations.AlterField(
            model_name='roadconditionsconfiguration',
            name='tts_use_weather_schedule',
            field=models.BooleanField(default=False, help_text='Resolve the current WeatherConfig schedule through Weather Voice Personas. This is the active road-report voice mode and must be enabled; when off, generation fails clearly because the retired legacy path is unavailable.'),
        ),
        migrations.AlterField(
            model_name='roadconditionsconfiguration',
            name='tts_voice',
            field=models.ForeignKey(blank=True, help_text='Reserved fixed logical voice. The active generator currently resolves Weather Voice Personas from the weather schedule instead.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='road_condition_configurations', to='tts.stationttsvoice'),
        ),
    ]
