# Generated by Django 5.2.15 on 2026-10-03 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('recording', 'Recording'), ('upload', 'Upload / import'), ('edit', 'Edit'), ('rendition', 'Rendition'), ('bed', 'Bed / production asset')], max_length=16)),
                ('owner_username', models.CharField(blank=True, help_text='Snapshot taken at creation so custody stays understandable after the user account is deleted.', max_length=150)),
                ('storage_key', models.CharField(max_length=64, unique=True)),
                ('sha256', models.CharField(max_length=64)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('container', models.CharField(blank=True, default='', max_length=32)),
                ('codec', models.CharField(blank=True, default='', max_length=32)),
                ('sample_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('channels', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('decoded_duration_seconds', models.DecimalField(blank=True, decimal_places=6, help_text='Duration established by a full decode -- the only duration to trust.', max_digits=12, null=True)),
                ('header_duration_seconds', models.DecimalField(blank=True, decimal_places=6, help_text='Duration the container claims; absent for e.g. browser WebM. Evidence only.', max_digits=12, null=True)),
                ('probe', models.JSONField(blank=True, default=dict, help_text='Bounded, whitelisted technical evidence (never raw tool output).')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('declared_content_type', models.CharField(blank=True, max_length=127)),
                ('validation_state', models.CharField(choices=[('unvalidated', 'Not yet validated'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='unvalidated', max_length=12)),
                ('validation_code', models.CharField(blank=True, help_text='Stable result code. While unvalidated it may hold the code of the last infrastructure failure (the media was NOT judged invalid).', max_length=48)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('recipe_key', models.CharField(blank=True, max_length=64)),
                ('recipe_version', models.PositiveIntegerField(blank=True, null=True)),
                ('recipe_params_digest', models.CharField(blank=True, max_length=64)),
                ('toolchain', models.CharField(blank=True, max_length=200)),
                ('retention_state', models.CharField(choices=[('present', 'Present'), ('purged', 'Purged (bytes removed)')], default='present', max_length=10)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derivatives', to='production.productionmedia')),
                ('owner', models.ForeignKey(blank=True, help_text='Custody of the bytes, not authority over any workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'production media',
                'verbose_name_plural': 'production media',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='production_media_sha256_hex'), models.CheckConstraint(condition=models.Q(('storage_key__regex', '^[0-9a-f]{2}/[0-9a-f]{32}$')), name='production_media_storage_key_shape'), models.CheckConstraint(condition=models.Q(('byte_size__gt', 0)), name='production_media_byte_size_positive'), models.CheckConstraint(condition=models.Q(models.Q(('kind__in', ('edit', 'rendition')), _negated=True), ('derived_from__isnull', False), _connector='OR'), name='production_media_derived_requires_parent'), models.CheckConstraint(condition=models.Q(models.Q(('purged_at__isnull', True), ('retention_state', 'present')), models.Q(('purged_at__isnull', False), ('retention_state', 'purged')), _connector='OR'), name='production_media_retention_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('validated_at__isnull', True), ('validation_state', 'unvalidated')), models.Q(('validated_at__isnull', False), ('validation_state__in', ('valid', 'invalid'))), _connector='OR'), name='production_media_validation_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('validation_state', 'valid'), _negated=True), models.Q(models.Q(('container', ''), _negated=True), models.Q(('codec', ''), _negated=True), ('sample_rate__isnull', False), ('channels__isnull', False), ('decoded_duration_seconds__isnull', False)), _connector='OR'), name='production_media_valid_has_facts')],
            },
        ),
    ]
