# Generated by Django 5.2.15 on 2026-07-08 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0041_add_wxalert_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OGRemoteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Master switch. Leave off until this box is the production on-air system -- kogr-sc's own OGRemote instance is still live and processing the same uploads/recalls otherwise.")),
                ('urgent_pa_replay_interval_minutes', models.PositiveIntegerField(default=20, help_text='How often the combined urgent/PA message clip re-inserts into the live queue while at least one message is still active (not yet recalled by its producer). Checked on a tight fixed cadence and re-read fresh each time -- no restart needed after changing this.')),
                ('notify_email', models.EmailField(blank=True, default='', help_text='Address for OGRemote pipeline failure notifications. Blank disables.', max_length=254)),
            ],
            options={
                'verbose_name': 'OGRemote Configuration',
                'verbose_name_plural': 'OGRemote Configuration',
            },
        ),
        migrations.CreateModel(
            name='OGRemoteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_key', models.SlugField(help_text="Matches the category_key the remote API sends, e.g. 'cal_events'.", unique=True)),
                ('name', models.CharField(help_text='Internal label only.', max_length=100)),
                ('output_mode', models.CharField(choices=[('single', 'Single file (newest upload overwrites)'), ('accumulating', 'Accumulating (each submission is its own track)')], default='single', max_length=12)),
                ('recallable', models.BooleanField(default=True, help_text="Whether a producer-requested recall removes this category's delivered output (file + Track row).")),
                ('enabled', models.BooleanField(default=True)),
                ('artist_tag', models.CharField(blank=True, help_text="ID3 artist tag applied to delivered tracks, e.g. 'Calendar of Events'.", max_length=100)),
                ('target_category', models.ForeignKey(help_text='Library category delivered tracks land in.', on_delete=django.db.models.deletion.PROTECT, to='library.category')),
            ],
            options={
                'verbose_name': 'OGRemote Category',
                'verbose_name_plural': 'OGRemote Categories',
                'ordering': ['category_key'],
            },
        ),
    ]
