# Generated by Django 5.2.15 on 2026-07-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogremote', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogremoteconfig',
            name='poll_interval_minutes',
            field=models.PositiveIntegerField(default=2, help_text="How often get_available_uploads polls the OGRemote API for new uploads / recalls. Effective floor is 1 minute (the systemd timer's own cadence -- setting this lower makes it fire every 1 minute). kogr-sc ran this at 5 minutes; isadoraair ships at 2. Re-read fresh at the start of every poll fire, so a change here takes effect on the next tick with no restart needed."),
        ),
    ]
