# Generated by Django 5.2.15 on 2026-07-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiooutput',
            name='agc_enabled',
            field=models.BooleanField(default=False, help_text='Off by default — nothing changes until explicitly enabled and tuned.'),
        ),
        migrations.AddField(
            model_name='audiooutput',
            name='agc_makeup_gain_db',
            field=models.FloatField(default=3.0, help_text='Gain applied after compression, in dB, to bring the leveled signal back up.'),
        ),
        migrations.AddField(
            model_name='audiooutput',
            name='agc_ratio',
            field=models.FloatField(default=2.0, help_text='Compression ratio, e.g. 2.0 = 2:1. Higher = more compression.'),
        ),
        migrations.AddField(
            model_name='audiooutput',
            name='agc_soft_knee',
            field=models.BooleanField(default=True, help_text='Soft-knee (smooth) vs hard-knee transition into compression.'),
        ),
        migrations.AddField(
            model_name='audiooutput',
            name='agc_threshold',
            field=models.FloatField(default=0.3, help_text='Linear amplitude (0.0-1.0) above which compression kicks in.'),
        ),
    ]
