# Generated by Django 5.2.15 on 2026-07-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_audiooutput_agc_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_rate', models.PositiveIntegerField(choices=[(32000, '32 kHz'), (44100, '44.1 kHz'), (48000, '48 kHz'), (88200, '88.2 kHz'), (96000, '96 kHz')], default=48000, help_text='Not all audio hardware natively supports every rate — if in doubt, 44.1kHz matches most of the library and 48kHz is the safest general-purpose default.')),
            ],
            options={
                'verbose_name': 'Audio Pipeline',
                'verbose_name_plural': 'Audio Pipeline',
            },
        ),
    ]
