# Generated by Django 5.2.15 on 2026-07-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_audio_pipeline_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuckingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Off by default -- nothing ducks until enabled.')),
                ('duck_level_db', models.FloatField(default=-12.0, help_text='How much to attenuate deck/program audio while the mic is live, in dB (negative = quieter, e.g. -12 = roughly quarter volume). Ramped over ~500ms on PTT toggle, not instant.')),
            ],
            options={
                'verbose_name': 'Ducking Config',
                'verbose_name_plural': 'Ducking Config',
            },
        ),
        migrations.AddField(
            model_name='audioinput',
            name='gain_db',
            field=models.FloatField(default=0.0, help_text='Software gain applied to this input in the on-air mix, in dB. Independent of the hardware mixer controls below, which affect the analog capture stage itself.'),
        ),
        migrations.AddField(
            model_name='audioinput',
            name='mixer_control_values',
            field=models.JSONField(blank=True, default=dict, help_text="Last-applied value per ALSA mixer control name for this input's card (e.g. {'Capture': 80, 'Mic Boost': True}). Populated/edited via the admin's dynamically-rendered control fields below -- not meant to be hand-edited as raw JSON."),
        ),
    ]
