# Generated by Django 5.2.15 on 2026-07-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_duckingconfig_audioinput_gain_db_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDJAudioInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain_db', models.FloatField(default=6.0, help_text="Software gain applied to the incoming remote-DJ mic before it joins the on-air mix, in dB. Default is +6 dB to compensate for browser WebRTC's typical output level being noticeably lower than a locally-captured mic through the same preamp -- adjust after listening. Read at session start; changes take effect on the next Remote DJ connect.")),
            ],
            options={
                'verbose_name': 'Remote DJ Audio Input',
                'verbose_name_plural': 'Remote DJ Audio Input',
            },
        ),
    ]
