# Generated by Django 5.2.15 on 2026-07-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0005_remotedjaudioinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopipeline',
            name='program_gain_db',
            field=models.FloatField(default=-6.0, help_text='Attenuation applied to the summed master bus before it feeds StereoTool and the Studio Monitor. Negative values give StereoTool more input headroom; 0 dB is unity (no attenuation). Default -6 dB matches typical broadcast pre-processor practice.'),
        ),
    ]
