# Generated by Django 5.2.15 on 2026-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_program_gain_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopipeline',
            name='vu_meter_min_db',
            field=models.FloatField(default=-40.0, help_text='Bottom of the dashboard VU meter scale, in dBFS. -40 puts the color transitions (yellow at -20 dBFS = 0 VU, red at -6 dBFS) at 50% and 85% of the bar width. Lower values (e.g. -60) stretch the low end for finer detail in quiet program. Client-side display only -- takes effect on next dashboard reload, no engine restart.'),
        ),
    ]
