# Generated by Django 5.2.15 on 2026-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_vu_meter_min_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiooutput',
            name='mixer_control_values',
            field=models.JSONField(blank=True, default=dict, help_text="Last-applied value per ALSA output-side mixer control for this output's card (e.g. {'Master,0': 90, 'Headphone,0': 100}). Populated via the admin's dynamically-rendered fields, not meant to be hand-edited as raw JSON."),
        ),
    ]
