# Generated by Django 5.2.15 on 2026-08-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0009_audioinput_device_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiooutput',
            name='device_identity',
            field=models.CharField(blank=True, default='', help_text="The stable identity value for the chosen kind above -- for 'ALSA card ID', the short id shown in brackets by `cat /proc/asound/cards` (e.g. 'PCH', 'CODEC'), NOT the numeric index. Ignored if device_identity_kind is blank.", max_length=64),
        ),
        migrations.AddField(
            model_name='audiooutput',
            name='device_identity_kind',
            field=models.CharField(blank=True, choices=[('', 'Legacy (raw device path only, no automatic recovery)'), ('alsa_card_id', 'ALSA card ID (stable across re-enumeration)')], default='', help_text="How to identify this hardware across a hotplug event. Leave blank to keep today's behavior (no automatic recovery on device loss, though a lost/blocked output still can't poison a sibling output's audio -- see engine.py's [P0] 1.3C containment). 'ALSA card ID' additionally enables automatic rebuild-on-return for this output.", max_length=32),
        ),
    ]
