# Generated by Django 5.2.15 on 2026-09-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_audiooutput_device_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duckingconfig',
            name='ptt_auto_manual_enabled',
            field=models.BooleanField(default=True, help_text='When enabled, taking either the Studio Mic or Remote DJ mic live automatically changes Auto to Manual and restores Auto when the final mic releases, but only if PTT caused Manual mode. When disabled, PTT never changes Auto/Manual mode; select Manual explicitly when desired. Read fresh by the engine on each PTT/mic transition -- no restart needed.'),
        ),
    ]
