# Generated by Django 5.2.15 on 2026-07-30 04:38

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0073_alter_category_rbds_ptyn'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('requester_name', models.CharField(blank=True, default='', max_length=100)),
                ('dedication_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('no_slot_soon', 'No slot soon'), ('fulfilled', 'Fulfilled'), ('unavailable', 'Unavailable'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('log_item', models.ForeignKey(blank=True, help_text='The specific LogItem this request was swapped into, once fulfilled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_song_request', to='library.logitem')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song_requests', to='library.track')),
            ],
            options={
                'verbose_name': 'Song Request',
                'verbose_name_plural': 'Song Requests',
                'ordering': ['submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WebRequestConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch. Off by default -- nothing is synced to the public site, nothing is polled, nothing is fulfilled, until this is on.')),
                ('open_slots', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, help_text='Hour x day-of-week slots OPEN for requests, encoded as day_of_week*24 + hour (0-167, Monday=0), station-local time -- same encoding as Track.blocked_slots. Empty = no hours open (safe default). Opposite polarity from Track.blocked_slots -- this is an allow-list, not a block-list.', size=None)),
                ('max_fulfilled_per_hour', models.PositiveSmallIntegerField(default=4, help_text="Ceiling on how many requests get swapped into music slots within any rolling clock hour, so automatic rotation isn't entirely displaced by a run of requests. Requests beyond the cap simply stay pending and roll into the next hour's budget rather than being rejected.")),
                ('lookahead_warning_minutes', models.PositiveSmallIntegerField(default=60, help_text="If no eligible music-kind slot is found within this many minutes of a request arriving (checked against both the availability grid and each candidate hour's actual resolved Rotation), the request is reported to the public site as 'no_slot_soon' instead of 'pending' -- still queued and still eligible to fulfill, just flagged so the site can set the requester's expectations. Re-evaluated every cycle, so a request can move between pending and no_slot_soon as the lookahead window's contents change.")),
                ('expire_after_hours', models.PositiveSmallIntegerField(default=6, help_text="A request that's neither fulfilled nor found a near-term slot within this many hours of submission is marked 'expired' and stops being retried.")),
            ],
            options={
                'verbose_name': 'Web Request Configuration',
                'verbose_name_plural': 'Web Request Configuration',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['open_slots'], name='webrequests_open_sl_ee0dca_gin')],
            },
        ),
    ]
