# Generated by Django 5.2.15 on 2026-07-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrequests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text="Set the moment status moves into ANY terminal value (fulfilled / expired / unavailable) -- distinct from fulfilled_at, which only covers the fulfilled case. Drives the status-push safety window: a terminal status keeps getting reported for a while after resolved_at, not just once, so a single dropped push can't leave the public site showing stale status.", null=True),
        ),
    ]
