# Generated by Django 5.2.15 on 2026-07-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrequests', '0002_songrequest_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='estimated_play_time',
            field=models.DateTimeField(blank=True, help_text='Best-guess air time, recomputed every refresh_song_request_statuses cycle from a FIFO pass over the upcoming open, music-kind LogItems (capped per hour by max_fulfilled_per_hour). Advisory only, for showing the requester a guess -- the actual fulfillment decision happens at engine queue-advance time and can land in a different slot than this estimate. Null while status is no_slot_soon or any terminal status.', null=True),
        ),
    ]
