# Generated by Django 5.2.15 on 2026-07-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrequests', '0003_songrequest_estimated_play_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrequestconfig',
            name='notify_email',
            field=models.EmailField(blank=True, default='', help_text='Address for web-requests-ingest pipeline failure notifications. Blank disables.', max_length=254),
        ),
    ]
