# Generated by Django 5.2.15 on 2026-07-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrequests', '0004_webrequestconfig_notify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrequest',
            name='estimated_play_time',
            field=models.DateTimeField(blank=True, help_text="While pending: a best-guess air time, recomputed every refresh_song_request_statuses cycle by checking each upcoming open, music-kind LogItem for real eligibility (recency included) rather than just chronological order. Advisory only until fulfilled -- the actual fulfillment can land in a different slot than a given cycle's guess. Once fulfilled: the real, certain scheduled_time of the LogItem it landed in, not a guess. Null while status is no_slot_soon, expired, or unavailable.", null=True),
        ),
    ]
