# Generated by Django 5.2.15 on 2026-07-31 23:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_scheduled_status(apps, schema_editor):
    """Reinterprets pre-existing 'fulfilled' rows under the new
    scheduled-vs-fulfilled split. Under the old code, fulfilled_at/
    resolved_at were written at ASSIGNMENT time, not air time -- so
    those old values are exactly what scheduled_at is supposed to mean.

    fulfilled + log_item present + played_at set (genuinely aired):
    status stays fulfilled, but timestamps are re-derived from what's
    actually true now -- the old fulfilled_at becomes scheduled_at, and
    fulfilled_at/resolved_at/estimated_play_time move to the real
    played_at.

    fulfilled + log_item present + played_at NULL (assigned, not yet
    aired -- could still be a perfectly valid, still-upcoming
    assignment, not necessarily lost): becomes scheduled, with
    fulfilled_at/resolved_at cleared (a scheduled row should never carry
    those). Whether it's ACTUALLY still valid or was stranded by a
    rollover gets sorted out by the first post-deploy run of
    refresh_song_request_statuses using live engine state, not guessed
    here.

    fulfilled + log_item NULL: intentionally left untouched. Ambiguous
    in a way the other two cases aren't -- could be a genuinely-aired
    request whose LogItem was cleaned up long after the fact (log_item
    is on_delete=SET_NULL) -- and shouldn't be resolved by an
    irreversible migration guess. See the separate, review-first
    reconcile_orphaned_fulfilled_requests management command."""
    SongRequest = apps.get_model("webrequests", "SongRequest")
    now = django.utils.timezone.now()

    for req in SongRequest.objects.filter(
        status="fulfilled", log_item__isnull=False, log_item__played_at__isnull=False,
    ).select_related("log_item"):
        SongRequest.objects.filter(id=req.id).update(
            scheduled_at=req.fulfilled_at,
            fulfilled_at=req.log_item.played_at,
            resolved_at=req.log_item.played_at,
            estimated_play_time=req.log_item.played_at,
            status_updated_at=now,
        )

    unaired = SongRequest.objects.filter(
        status="fulfilled", log_item__isnull=False, log_item__played_at__isnull=True,
    )
    for req in unaired:
        SongRequest.objects.filter(id=req.id).update(
            status="scheduled", scheduled_at=req.fulfilled_at,
            fulfilled_at=None, resolved_at=None, status_updated_at=now,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0074_add_web_requests_nav_item'),
        ('webrequests', '0005_alter_songrequest_estimated_play_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='Set the moment this request was assigned a specific LogItem (status became scheduled). Retained as history even after fulfillment; cleared whenever the request returns to pending/no_slot_soon/unavailable.', null=True),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='status_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Version/ordering timestamp the public site uses to reject an out-of-order or delayed status push -- bumped explicitly by every code path that changes status OR estimated_play_time (deliberately NOT auto_now: that fires on QuerySet.update() not at all, which is how nearly every transition here writes for concurrency safety, and silently overrides an explicitly-assigned value on .save(), so it added a footgun with no actual benefit here).'),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='estimated_play_time',
            field=models.DateTimeField(blank=True, help_text="While pending: a best-guess air time, recomputed every refresh_song_request_statuses cycle by checking each upcoming open, music-kind LogItem for real eligibility (recency included) rather than just chronological order. Advisory only until scheduled -- the actual assignment can land in a different slot than a given cycle's guess. Once scheduled: the real, certain scheduled_time (or live drift-corrected ETA) of the LogItem it landed in. Once fulfilled: the real air timestamp, matching fulfilled_at. Null while status is no_slot_soon, expired, or unavailable.", null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, help_text='Set the moment the track ACTUALLY started airing (status became fulfilled) -- not when it was merely assigned a slot. See scheduled_at for that.', null=True),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='log_item',
            field=models.ForeignKey(blank=True, help_text='The specific LogItem this request was assigned to, once scheduled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_song_request', to='library.logitem'),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('no_slot_soon', 'No slot soon'), ('scheduled', 'Scheduled'), ('fulfilled', 'Fulfilled'), ('unavailable', 'Unavailable'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16),
        ),
        migrations.RunPython(backfill_scheduled_status, migrations.RunPython.noop),
    ]
