# Generated by Django 5.2.15 on 2026-08-01 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0074_add_web_requests_nav_item'),
        ('webrequests', '0006_scheduled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='intro_log_item',
            field=models.ForeignKey(blank=True, help_text="Set the moment intro_track is actually spliced into the live queue ahead of log_item -- the reinsertion guard (an intro is only ever spliced once per song assignment) and the restart-recovery key. Cleared whenever the request's assignment is abandoned (pending/no_slot_soon/unavailable/expired); retained on fulfilled as historical evidence the pairing aired correctly.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedication_intro_for_request', to='library.logitem'),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='intro_track',
            field=models.ForeignKey(blank=True, help_text='The synthesized spoken-intro clip for this request, once rendered. Never cleared by reconciliation regardless of status -- reusable if the request reschedules, and a clean audit trail even for a terminal request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedication_intro_requests', to='library.track'),
        ),
    ]
