# Generated by Django 5.2.10 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tts", "0001_initial"),
        ("webrequests", "0007_dedication_intro_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="webrequestconfig",
            name="dedication_tts_timeout_seconds",
            field=models.PositiveIntegerField(default=30, help_text="Future shared-TTS timeout for a short dedication intro; not active before cutover."),
        ),
        migrations.AddField(
            model_name="webrequestconfig",
            name="dedication_tts_voice",
            field=models.ForeignKey(blank=True, help_text="Logical voice reserved for the later shared-TTS dedication cutover. Blank keeps the current production synthesis path unchanged.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="dedication_configurations", to="tts.stationttsvoice"),
        ),
    ]
