# Generated by Django 5.2.15 on 2026-09-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
        ('webrequests', '0008_webrequestconfig_dedication_tts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webrequestconfig',
            name='dedication_tts_timeout_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Shared-TTS timeout for each short dedication intro.'),
        ),
        migrations.AlterField(
            model_name='webrequestconfig',
            name='dedication_tts_voice',
            field=models.ForeignKey(blank=True, help_text='Logical station voice used for spoken dedication intros. Blank disables intro synthesis while the requested song still airs.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dedication_configurations', to='tts.stationttsvoice'),
        ),
    ]
