# Generated by Django 5.2.15 on 2026-09-09 05:57

import django.core.validators
import webrequests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webrequests', '0009_alter_webrequestconfig_dedication_tts_timeout_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrequestconfig',
            name='dedication_anonymous_message_template',
            field=models.CharField(default="Now here's {title} by {artist}, {dedication_message}", help_text='Used when a dedication message is present but no requester name was given. Allowed placeholders: {title} {artist} {requester_name} {dedication_message}.', max_length=512, validators=[webrequests.models.validate_dedication_template_field]),
        ),
        migrations.AddField(
            model_name='webrequestconfig',
            name='dedication_anonymous_request_template',
            field=models.CharField(default="Now here's {title} by {artist}.", help_text='Used when neither a requester name nor a dedication message was given. Allowed placeholders: {title} {artist} {requester_name} {dedication_message}.', max_length=512, validators=[webrequests.models.validate_dedication_template_field]),
        ),
        migrations.AddField(
            model_name='webrequestconfig',
            name='dedication_message_spoken_limit',
            field=models.PositiveSmallIntegerField(default=300, help_text="Local, authoritative on-air length cap for a normalized dedication message -- independent of (and much smaller than) the public site's own 2,000-character transport limit. A message that exceeds this is never truncated: the intro is simply not generated and the requested song still airs plainly.", validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='webrequestconfig',
            name='dedication_named_message_template',
            field=models.CharField(default="Now here's {title} by {artist}, {dedication_message} Thanks {requester_name} for your dedication.", help_text='Used when a requester name AND a dedication message are both present. Allowed placeholders: {title} {artist} {requester_name} {dedication_message}.', max_length=512, validators=[webrequests.models.validate_dedication_template_field]),
        ),
        migrations.AddField(
            model_name='webrequestconfig',
            name='dedication_named_request_template',
            field=models.CharField(default="Now here's {title} by {artist}. Thanks {requester_name} for your request.", help_text='Used when a requester name is present but no dedication message was given. Allowed placeholders: {title} {artist} {requester_name} {dedication_message}.', max_length=512, validators=[webrequests.models.validate_dedication_template_field]),
        ),
    ]
