# Generated by Django 5.2.10 on 2026-08-22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PiperVoiceModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model_id", models.SlugField(help_text="Stable model identity; not a filename or filesystem path.", max_length=128, unique=True)),
                ("model_filename", models.CharField(help_text="Basename of the .onnx file under the canonical Piper asset root.", max_length=255)),
                ("config_filename", models.CharField(help_text="Basename of the paired .onnx.json file under the canonical Piper asset root.", max_length=255)),
                ("model_sha256", models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message="Enter a lowercase 64-character SHA-256 digest.", regex="^[0-9a-f]{64}$")])),
                ("config_sha256", models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message="Enter a lowercase 64-character SHA-256 digest.", regex="^[0-9a-f]{64}$")])),
                ("language", models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message="Enter a language identifier such as en-us or en_US.", regex="^[A-Za-z][A-Za-z0-9_-]{0,31}$")])),
                ("sample_rate_hz", models.PositiveIntegerField(help_text="Exact native sample rate declared by this model's JSON configuration.")),
            ],
            options={"verbose_name": "Piper Voice Model", "verbose_name_plural": "Piper Voice Models", "ordering": ["model_id"]},
        ),
        migrations.CreateModel(
            name="StationTTSVoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.SlugField(help_text="Stable logical station voice ID exposed to callers.", max_length=128, unique=True)),
                ("enabled", models.BooleanField(default=False, help_text="Disabled voices cannot be resolved or synthesized.")),
                ("engine", models.CharField(choices=[("kokoro", "Kokoro"), ("piper", "Piper")], max_length=16)),
                ("provider_voice", models.SlugField(blank=True, help_text="Kokoro's native voice ID. Blank for Piper voices.", max_length=128)),
                ("language", models.CharField(default="en-us", help_text="Default synthesis language. Piper must match its model-bound language.", max_length=32, validators=[django.core.validators.RegexValidator(message="Enter a language identifier such as en-us or en_US.", regex="^[A-Za-z][A-Za-z0-9_-]{0,31}$")])),
                ("speed", models.FloatField(default=1.0, help_text="Default positive speed multiplier; callers may deliberately override it.")),
                ("piper_model", models.ForeignKey(blank=True, help_text="Required only for a Piper logical voice.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="station_voices", to="tts.pipervoicemodel")),
            ],
            options={"verbose_name": "Station TTS Voice", "verbose_name_plural": "Station TTS Voices", "ordering": ["name"]},
        ),
    ]
