# Generated by Django 5.2.15 on 2026-07-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AircheckConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_format', models.CharField(choices=[('he_aac', 'HE-AAC (fdkaac)'), ('mp3', 'MP3 (libmp3lame)'), ('flac', 'FLAC (lossless)'), ('wav', 'WAV (uncompressed PCM)')], default='he_aac', help_text='ffmpeg encoder. HE-AAC (fdkaac) is the small, compliance-archive default (~30 MB/hr at 64k). MP3 320 is the high-quality option (~140 MB/hr) for airchecks you might want to review or reuse. FLAC/WAV for lossless (~1.4 GB/hr for WAV).', max_length=16)),
                ('bitrate', models.CharField(blank=True, default='64k', help_text="ffmpeg -b:a value (e.g. '64k', '128k', '320k'). Ignored for FLAC/WAV. Blank falls back to the format's default (64k for HE-AAC, 320k for MP3).", max_length=8)),
                ('source_device', models.CharField(default='plughw:3,1', help_text="ALSA device the ffmpeg -i argument reads from. Default 'plughw:3,1' = post-StereoTool loopback (same source the encoders read). Change to a dsnoop alias if simultaneous encoder+aircheck reads collide.", max_length=64)),
                ('output_directory', models.CharField(default='/srv/isadoraair/aircheck', help_text="Directory where aircheck files land. Created on first record if it doesn't exist. Should live on a partition with plenty of headroom -- a full day of 320 mp3 is ~3.4 GB.", max_length=255)),
                ('filename_template', models.CharField(default='aircheck-%Y%m%d-%H%M%S', help_text="Python strftime template (extension is added automatically per audio_format). Default 'aircheck-%%Y%%m%%d-%%H%%M%%S' -> 'aircheck-20261225-143012.mp3'. Sorts lexically = chronologically.", max_length=100)),
            ],
            options={
                'verbose_name': 'Aircheck Configuration',
                'verbose_name_plural': 'Aircheck Configuration',
            },
        ),
        migrations.CreateModel(
            name='AircheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('filename', models.CharField(max_length=512)),
                ('audio_format', models.CharField(choices=[('he_aac', 'HE-AAC (fdkaac)'), ('mp3', 'MP3 (libmp3lame)'), ('flac', 'FLAC (lossless)'), ('wav', 'WAV (uncompressed PCM)')], max_length=16)),
                ('bitrate', models.CharField(blank=True, max_length=8)),
                ('source_device', models.CharField(max_length=64)),
                ('ffmpeg_pid', models.PositiveIntegerField(blank=True, null=True)),
                ('still_running', models.BooleanField(default=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('exit_note', models.CharField(blank=True, help_text='Populated on stop with a short note if ffmpeg exited non-zero, was killed abnormally, or hit an edge case. Blank on a clean session.', max_length=200)),
            ],
            options={
                'verbose_name': 'Aircheck Session',
                'verbose_name_plural': 'Aircheck Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
