# Generated by Django 5.2.15 on 2026-07-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircheckconfig',
            name='source_device',
            field=models.CharField(default='airtap', help_text="ALSA device the ffmpeg -i argument reads from. Default 'airtap' = dsnoop alias defined in /etc/asound.conf that locks to the post-StereoTool loopback (hw:Loopback_1,1,0) and lets encoders + aircheck share one capture stream. Change to plughw:3,1 only for diagnostics -- a bare hw open collides with encoders and lands on a silent unpaired subdevice.", max_length=64),
        ),
    ]
