# Generated by Django 5.2.15 on 2026-08-23 20:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('initiated_by_username', models.CharField(editable=False, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('installed_release_id', models.CharField(max_length=32)),
                ('target_release_id', models.CharField(max_length=32)),
                ('installed_commit', models.CharField(max_length=40)),
                ('target_commit', models.CharField(max_length=40)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('planned', 'Planned'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('manual_intervention_required', 'Manual intervention required'), ('interrupted', 'Interrupted'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('current_step', models.CharField(blank=True, default='', max_length=64)),
                ('progress_detail', models.CharField(blank=True, default='', max_length=500)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict)),
                ('plan_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('failure_classification', models.CharField(blank=True, default='', max_length=64)),
                ('failure_detail', models.TextField(blank=True, default='')),
                ('requires_manual_intervention', models.BooleanField(default=False)),
                ('completed_log_snapshot', models.TextField(blank=True, default='')),
                ('active_lock', models.SmallIntegerField(blank=True, default=None, editable=False, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Update Job',
                'verbose_name_plural': 'Update Jobs',
                'ordering': ['-created_at'],
                'permissions': [('can_update_isadoraair', 'Can execute IsadoraAir updates')],
                'constraints': [
                    models.UniqueConstraint(fields=('active_lock',), name='updatecenter_one_active_job'),
                    models.CheckConstraint(condition=models.Q(('active_lock__isnull', True), ('active_lock', 1), _connector='OR'), name='updatecenter_active_lock_null_or_one'),
                ],
            },
        ),
    ]
