# Generated by Django 5.2.15 on 2026-09-28 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updatecenter', '0002_alter_updatejob_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='updatejob',
            name='migration_plan_review',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='MigrationPlanApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_release_id', models.CharField(max_length=32)),
                ('target_commit', models.CharField(max_length=40)),
                ('migration_plan_digest', models.CharField(max_length=64)),
                ('manual_operations_snapshot', models.JSONField(blank=True, default=list)),
                ('approved_by_username', models.CharField(editable=False, max_length=150)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='updatecenter.updatejob')),
            ],
            options={
                'verbose_name': 'Migration Plan Approval',
                'verbose_name_plural': 'Migration Plan Approvals',
                'ordering': ['-approved_at'],
                'constraints': [models.UniqueConstraint(fields=('target_release_id', 'migration_plan_digest'), name='updatecenter_one_approval_per_release_digest')],
            },
        ),
    ]
