# Generated by Django 5.2.15 on 2026-07-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_lat', models.FloatField(default=39.13, help_text='Station latitude -- used for sunrise/sunset (day/night sky wording).')),
                ('station_lon', models.FloatField(default=-97.7, help_text='Station longitude.')),
                ('sun_alt_threshold_deg', models.FloatField(default=3.0, help_text="Solar altitude (degrees) above which it's considered daytime.")),
                ('nws_alert_zone', models.CharField(default='KSC143', help_text='NWS public forecast zone for active alerts, e.g. KSC143.', max_length=16)),
                ('nws_forecast_office', models.CharField(default='TOP', help_text='NWS forecast office code, e.g. TOP (Topeka).', max_length=8)),
                ('nws_forecast_grid_x', models.PositiveIntegerField(default=10)),
                ('nws_forecast_grid_y', models.PositiveIntegerField(default=53)),
                ('nws_cloud_stations', models.CharField(default='KCNK,KSLN', help_text='Comma-separated METAR station codes used to blend sky condition.', max_length=64)),
                ('voice_schedule', models.JSONField(default=list, help_text='List of [voice, start_hour, end_hour] triples, local time, 0-23, end inclusive. A range may wrap past midnight (start > end). Must cover every hour with no gaps. voice is "day" or "night". Example: [["day",3,8],["night",9,14],["day",15,20],["night",21,2]]')),
                ('notify_email', models.EmailField(blank=True, default='', help_text='Address for weather-pipeline failure notifications. Blank disables.', max_length=254)),
            ],
            options={
                'verbose_name': 'Weather Configuration',
                'verbose_name_plural': 'Weather Configuration',
            },
        ),
    ]
