# Generated by Django 5.2.15 on 2026-07-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherconfig',
            name='alert_sound_device',
            field=models.CharField(default='plughw:4,0', help_text="ALSA device the beep is played to -- a dedicated loopback feeding StereoTool's second input, independent of the engine's own output.", max_length=32),
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='alert_sound_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for the watch/warning alert beep. Off overrides everything below -- no beep plays regardless of active alert status. Separate from the WxAlert spoken-statement pipeline, which is unaffected by this switch.'),
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='alert_sound_interval_seconds',
            field=models.PositiveIntegerField(default=600, help_text='How often the beep replays while a watch/warning remains active, in seconds. Re-read fresh every check -- no restart needed.'),
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='alert_sound_path',
            field=models.CharField(default='/home/jreed/weather-ingest/media/weather_beeps.flac', help_text='Path to the alert beep audio file, played directly to ALSA (not through the playback engine) while a watch/warning is active.', max_length=255),
        ),
    ]
