# Generated by Django 5.2.15 on 2026-07-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherconfig_alert_sound_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherconfig',
            name='alert_sound_gain_db',
            field=models.FloatField(default=-12.0, help_text="Gain applied to the beep before it reaches StereoTool's Input 2, in dB (negative = quieter, 0 = unchanged from the source file). The file plays at full level otherwise, which was found to drive the processor's AGC down hard on air -- tune this down until the beep sits at a normal announcement level."),
        ),
    ]
