# Generated by Django 5.2.15 on 2026-07-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherconfig_alert_sound_gain_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherconfig',
            name='alert_sound_path',
            field=models.CharField(default='', help_text='Path to the alert beep audio file, played directly to ALSA (not through the playback engine) while a watch/warning is active. Blank disables the beep entirely -- the beep file is operator-supplied and station-specific (WEA-style pattern or otherwise); set this to its absolute path once it exists.', max_length=255),
        ),
    ]
