# Generated by Django 5.2.15 on 2026-07-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_weatherconfig_alert_sound_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmberAlertConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text="Master switch. When off, the pipeline never polls IPAWS and never speaks or inserts anything. Everything else in this form is inert while off. Off by default so a fresh install doesn't start airing AMBER Alerts before the operator has reviewed the terms and area filters.")),
                ('ipaws_base_url', models.URLField(default='https://apps.fema.gov/IPAWSOPEN_EAS_SERVICE', help_text="IPAWS OPEN service root. The poller reads /rest/feed under this base for the Atom summary and /rest/eas/{id} for each full CAP message. Only change this if FEMA moves the endpoint or if you're pointing at a private mirror for testing.")),
                ('event_codes', models.CharField(default='BLU,CAE,MEP', help_text='Comma-separated CAP/SAME event codes to include. Defaults cover the three we care about: BLU (Blue Alert -- law enforcement officer down), CAE (Child Abduction Emergency -- AMBER), MEP (Missing and Endangered Persons).', max_length=200)),
                ('same_codes', models.CharField(default='020027,020029,020041,020053,020105,020123,020139,020169,020000', help_text='Comma-separated 6-digit SAME area codes to include. First two digits are the state FIPS (Kansas = 20), last four are the county FIPS (000 for statewide). Defaults cover the eight KS counties in the KOGR-LP listening area plus 020000 for state-scoped alerts.', max_length=500)),
                ('poll_cadence_minutes', models.PositiveIntegerField(default=5, help_text="How often the poller checks the IPAWS feed. 5 minutes matches the general practice for voluntary broadcasters and stays under FEMA's rate ceiling. Lower is more responsive but more API load; higher risks delayed broadcast of a time-sensitive alert.")),
                ('include_instruction_in_forecast', models.BooleanField(default=True, help_text="For AMBER-family alerts, the 'instruction' field is usually the tip-line phone number -- the whole point of the broadcast. Default ON means it's included in BOTH the urgent insert AND the forecast append (unlike weather safety instructions, which we drop from the forecast). Turn off if you want the forecast to summarize only.")),
            ],
            options={
                'verbose_name': 'AMBER Alert Configuration',
                'verbose_name_plural': 'AMBER Alert Configuration',
            },
        ),
    ]
