# Generated by Django 5.2.15 on 2026-08-09 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0077_uitheme_deck_transport_disabled_opacity'),
        ('weather', '0005_amber_alert_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherconfig',
            name='alert_sound_device',
        ),
        migrations.RemoveField(
            model_name='weatherconfig',
            name='alert_sound_gain_db',
        ),
        migrations.RemoveField(
            model_name='weatherconfig',
            name='alert_sound_path',
        ),
        migrations.AddField(
            model_name='weatherconfig',
            name='alert_sound_cart',
            field=models.ForeignKey(blank=True, help_text="The FX Cart fired while a qualifying watch/warning remains active. Playback travels through IsadoraAir's normal FX/program bus (same path as any other cart fire), so it's present on air and in studio/remote-DJ monitoring -- not a separate weather-only audio path. The cart's own filepath, gain, and retrigger mode apply as usual; nothing here overrides them. Blank/deleted cart disables the beep, same as leaving alert_sound_enabled off.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_alert_configs', to='library.fxcart', verbose_name='Alert FX Cart'),
        ),
    ]
