# Generated by Django 5.2.10 on 2026-08-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tts", "0001_initial"),
        ("weather", "0006_remove_weatherconfig_alert_sound_device_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherVoicePersona",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slot", models.SlugField(help_text="Stable key referenced by WeatherConfig.voice_schedule, such as day or night.", max_length=64, unique=True)),
                ("display_name", models.CharField(blank=True, default="", help_text="Feature-facing short persona name; never passed to a TTS provider.", max_length=100)),
                ("full_name", models.CharField(blank=True, default="", help_text="Listener-facing full persona name; never passed to a TTS provider.", max_length=150)),
                ("signoff", models.TextField(blank=True, default="", help_text="Weather-specific wording; never passed into TTS voice resolution.")),
                ("tts_voice", models.ForeignKey(blank=True, help_text="Logical station voice. Blank is a safe unconfigured state.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name="weather_personas", to="tts.stationttsvoice")),
            ],
            options={"verbose_name": "Weather Voice Persona", "verbose_name_plural": "Weather Voice Personas", "ordering": ["slot"]},
        ),
    ]
