# Generated by Django 5.2.15 on 2026-09-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_weathervoicepersona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherconfig',
            name='voice_schedule',
            field=models.JSONField(default=list, help_text='List of [persona_slot, start_hour, end_hour] triples, local time, 0-23, end inclusive. A range may wrap past midnight (start > end) and every hour must be covered exactly once. Slot keys are arbitrary Weather Voice Persona identifiers. Example: [["morning_host",5,11],["default",12,4]]'),
        ),
        migrations.AlterField(
            model_name='weathervoicepersona',
            name='slot',
            field=models.SlugField(help_text='Arbitrary stable key referenced by WeatherConfig.voice_schedule, such as default or morning_host.', max_length=64, unique=True),
        ),
    ]
