# Generated by Django 5.2.15 on 2026-09-09 03:06

import weather.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_alter_weatherconfig_voice_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherconfig',
            name='alert_sound_trigger_events',
            field=models.JSONField(default=weather.models._default_alert_sound_trigger_events, help_text='NWS event names (e.g. "Tornado Warning") that activate the repeating Alert Beep FX Cart -- case-insensitive substring match against the NWS event name, matching current production behavior. This does NOT control generated spoken Weather or AMBER alert statements (see WxAlert/wx_alert.mp3 readiness in Weather Setup Status for those) -- it governs only the repeating sonar/ping FX Cart selected above. An empty list means no NWS event ever triggers the beep. Nullable so the protected updater\'s schema classifier can add this column automatically (a non-null AddField must have a simple scalar default, which a JSON list can never be) -- see normalize_alert_sound_trigger_events() below, which treats a stored NULL as exactly these same four legacy defaults, never as malformed or as an operator\'s explicit empty choice.', null=True),
        ),
        migrations.AlterField(
            model_name='weatherconfig',
            name='nws_alert_zone',
            field=models.CharField(default='KSC143', help_text="NWS county/zone UGC used to look up active alerts, e.g. KSC143 -- a COUNTY UGC (the 'C' in KSC143), not a public forecast-zone code ('Z'). Deliberately county-based: NWS alert lookup by county returns both county-based alerts and zone-based alerts mapped to that county, so this is not a mistake to 'correct' to a KSZ... code. The NWS Setup discovery action above always discovers and offers this same county UGC, never a forecast-zone code.", max_length=16),
        ),
    ]
