# Generated by Django 5.2.15 on 2026-07-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('systemd', 'Systemd Service'), ('disk', 'Disk Usage'), ('cpu', 'CPU Usage'), ('memory', 'Memory Usage'), ('temperature', 'Temperature'), ('transmitter_param', 'Transmitter Parameter'), ('transmitter_indicator', 'Transmitter Status Indicator'), ('audio_silence', 'Audio Silence (Liquidsoap)')], max_length=24)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('systemd_unit', models.CharField(blank=True, help_text='Unit name, e.g. isadoraair-engine.service.', max_length=100)),
                ('disk_path', models.CharField(blank=True, help_text='Mount point to check, e.g. / or /srv/isadoraair.', max_length=255)),
                ('thermal_zone_label', models.CharField(blank=True, help_text="A psutil.sensors_temperatures() entry label to watch specifically (e.g. 'Package id 0' under the 'coretemp' chip). Leave blank to watch the highest current reading across every sensor on the box.", max_length=64)),
                ('transmitter_parameter', models.CharField(blank=True, help_text='COBALT get-parameter, e.g. psu.fwd_power, psu.vswr, psu.pa_temperature, psu.fan_speed_measured_fan1.', max_length=64)),
                ('transmitter_indicator', models.CharField(blank=True, help_text='COBALT indicator parameter, e.g. status.indicator.rf, status.indicator.vswr, status.indicator.temp, status.rf_interlock.', max_length=64)),
                ('fault_values', models.CharField(blank=True, help_text="Comma-separated values that mean FAULT (critical), e.g. 'R' or 'True'.", max_length=128)),
                ('warn_values', models.CharField(blank=True, help_text="Comma-separated values that mean WARNING (degraded, not fault), e.g. 'O'.", max_length=128)),
                ('silence_device_slug', models.CharField(blank=True, help_text='Matches encoders.services.encoder_manager._slug(input_device) — used to find /run/isadoraair/liquidsoap_silence_<slug>.json.', max_length=100)),
                ('warning_threshold', models.FloatField(blank=True, help_text="Value at which this check becomes WARNING. Percent for cpu/mem/disk; units vary by kind — see that kind's own help text.", null=True)),
                ('critical_threshold', models.FloatField(blank=True, help_text='Value at which this check becomes CRITICAL.', null=True)),
                ('threshold_direction', models.CharField(choices=[('above', 'Alert when ABOVE threshold'), ('below', 'Alert when BELOW threshold')], default='above', help_text='Most checks alert when the value climbs too high (disk/cpu/mem/temp/VSWR). Use BELOW for things where a drop is bad, e.g. forward power or fan RPM.', max_length=8)),
                ('consecutive_failures_required', models.PositiveSmallIntegerField(default=2, help_text='Consecutive bad polls needed before this check flips status and a notification fires — avoids alerting on a single transient blip.')),
                ('notify_on_warning', models.BooleanField(default=True)),
                ('notify_on_critical', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Monitor Check',
                'verbose_name_plural': 'Monitor Checks',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('recipients', models.TextField(blank=True, help_text='One email per line (or comma-separated). For SMS-via-carrier-gateway, use e.g. 5551234567@vtext.com — treated as a plain email address, no special handling needed.')),
                ('cooldown_minutes', models.PositiveIntegerField(default=30, help_text='Minimum time between repeat notifications for the same ongoing failure. Recovery notifications always send immediately.')),
            ],
            options={
                'verbose_name': 'Notification Config',
                'verbose_name_plural': 'Notification Config',
            },
        ),
        migrations.CreateModel(
            name='TransmitterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, help_text='Transmitter IP or hostname. Leave blank to disable transmitter polling.', max_length=255)),
                ('port', models.PositiveIntegerField(default=23, help_text="TCP port for the ASCII control protocol — confirm against the unit's own network settings.")),
                ('timeout_seconds', models.FloatField(default=3.0)),
                ('poll_interval_seconds', models.PositiveIntegerField(default=30, help_text='How often to poll the transmitter specifically — independent of the main monitor loop, since a TCP round-trip to RF hardware is slower than a local systemctl/psutil call.')),
            ],
            options={
                'verbose_name': 'Transmitter Config',
                'verbose_name_plural': 'Transmitter Config',
            },
        ),
    ]
