# Generated by Django 5.2.15 on 2026-07-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_seed_default_checks'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcheck',
            name='show_as_card',
            field=models.BooleanField(default=True, help_text='Uncheck to keep this check running and alerting but hide its own dashboard card -- useful when another card already displays its status (e.g. a transmitter indicator check whose value colors a paired parameter card, like TX RF Indicator coloring TX Forward Power).'),
        ),
        migrations.AddField(
            model_name='transmitterconfig',
            name='full_power_watts',
            field=models.FloatField(default=265.0, help_text='Forward power reading that counts as 100% on the Forward Power meter.'),
        ),
    ]
