# Generated by Django 5.2.15 on 2026-07-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_hide_folded_in_indicator_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorcheck',
            name='kind',
            field=models.CharField(choices=[('systemd', 'Systemd Service'), ('disk', 'Disk Usage'), ('cpu', 'CPU Usage'), ('memory', 'Memory Usage'), ('temperature', 'Temperature'), ('transmitter_param', 'Transmitter Parameter'), ('transmitter_indicator', 'Transmitter Status Indicator'), ('audio_silence', 'Audio Silence (Liquidsoap)'), ('rbds', 'RBDS Connection')], max_length=24),
        ),
    ]
