# Generated by Django 5.2.15 on 2026-07-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_monitorcheck_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerPeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_total', models.PositiveIntegerField(default=0, help_text='Highest sum-of-listeners-across-all-enabled-encoders value seen since peak_since_at. Updated live by the monitor tick.')),
                ('peak_since_at', models.DateTimeField(auto_now_add=True, help_text="When the current peak-tracking window started -- either engine first-boot or the operator's last reset.")),
                ('peak_reached_at', models.DateTimeField(blank=True, help_text="When peak_total was last raised. Blank if we haven't seen anyone since the last reset.", null=True)),
            ],
            options={
                'verbose_name': 'Listener Peak',
                'verbose_name_plural': 'Listener Peak',
            },
        ),
    ]
