# Generated by Django 5.2.15 on 2026-07-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_listenerpeak'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, max_length=64)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('repeat_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_repeated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Event',
                'verbose_name_plural': 'System Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'level'], name='monitoring__created_b92314_idx'), models.Index(fields=['category', '-created_at'], name='monitoring__categor_ad4009_idx')],
            },
        ),
    ]
