# Generated by Django 5.2.15 on 2026-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_systemevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcheck',
            name='encoder_group_slug',
            field=models.CharField(blank=True, help_text="Matches encoders.services.encoder_manager._slug(input_device) — used to find both /run/isadoraair/liquidsoap_silence_<slug>.json (Liquidsoap's own self-report) and /run/isadoraair/encoder_group_<slug>.json (the encoder manager's own process-supervision state). Same slug convention as silence_device_slug above -- a separate field rather than reusing that one, since this is a genuinely different check kind (the truthful AGGREGATE across manager/child/audio/Shoutcast signals, not audio silence alone) that an operator may or may not want configured alongside the existing Audio Silence check for the same group. Added 2026-08-05 after a real production outage where neither the existing systemd check nor the existing audio_silence check caught a Liquidsoap crash-loop -- see probe_encoder_group.", max_length=100),
        ),
        migrations.AddField(
            model_name='monitorcheck',
            name='encoder_group_systemd_unit',
            field=models.CharField(blank=True, help_text="Systemd unit backing the encoder manager itself, e.g. isadoraair-encoders.service — checked directly (reusing probe_systemd's own logic) as one of several signals this kind combines. Separate from the plain 'Systemd Service' kind's own systemd_unit field above so this check's config is self-contained rather than depending on another MonitorCheck row existing.", max_length=100),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='kind',
            field=models.CharField(choices=[('systemd', 'Systemd Service'), ('disk', 'Disk Usage'), ('cpu', 'CPU Usage'), ('memory', 'Memory Usage'), ('temperature', 'Temperature'), ('transmitter_param', 'Transmitter Parameter'), ('transmitter_indicator', 'Transmitter Status Indicator'), ('audio_silence', 'Audio Silence (Liquidsoap)'), ('encoder_group', 'Encoder Stream Health'), ('rbds', 'RBDS Connection')], max_length=24),
        ),
    ]
