# Generated by Django 5.2.15 on 2026-07-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0051_cdripconfig'),
        ('monitoring', '0007_systemevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcheck',
            name='log_slot_category',
            field=models.ForeignKey(blank=True, help_text="Category the track at log_slot_position MUST belong to. Reports critical if the current hour's log has no item at that position, or if the item's track's category doesn't match. Primary use: FCC-required legal ID at top of hour -- set position=0, category=Legal ID.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='library.category'),
        ),
        migrations.AddField(
            model_name='monitorcheck',
            name='log_slot_position',
            field=models.PositiveSmallIntegerField(default=0, help_text="Position (0-indexed) in the current hour's PlaylistLog to check. 0 = top-of-hour, which is the Legal ID slot on this station."),
        ),
        migrations.AlterField(
            model_name='monitorcheck',
            name='kind',
            field=models.CharField(choices=[('systemd', 'Systemd Service'), ('disk', 'Disk Usage'), ('cpu', 'CPU Usage'), ('memory', 'Memory Usage'), ('temperature', 'Temperature'), ('transmitter_param', 'Transmitter Parameter'), ('transmitter_indicator', 'Transmitter Status Indicator'), ('audio_silence', 'Audio Silence (Liquidsoap)'), ('rbds', 'RBDS Connection'), ('log_slot_category', 'Log Slot Category (top-of-hour ID tripwire)')], max_length=24),
        ),
    ]
