# Generated by Django 5.2.15 on 2026-08-09 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_monitorcheck_encoder_group_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenerpeak',
            name='tlh_hours',
            field=models.FloatField(default=0.0, help_text='Total Listening Hours: running sum, in hours, of sum-of-listeners-across-all-enabled-encoders x sample interval, accumulated every monitor tick since tlh_since_at. A cumulative measure, not a snapshot -- unlike peak_total, this only ever goes up between resets.'),
        ),
        migrations.AddField(
            model_name='listenerpeak',
            name='tlh_since_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text="When the current TLH accumulation window started -- either engine first-boot or the operator's last reset."),
            preserve_default=False,
        ),
    ]
