# Generated by Django 5.2.15 on 2026-08-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_listenerpeak_tlh_hours_listenerpeak_tlh_since_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listenerpeak',
            name='tlh_since_at',
            field=models.DateTimeField(auto_now_add=True, help_text="When the current TLH accumulation window started -- engine first-boot, the operator's last manual reset, or the last automatic monthly rollover (midnight on the 1st, station-local time)."),
        ),
    ]
