# Generated by Django 5.2.15 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0010_alter_listenerpeak_tlh_since_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmitterconfig",
            name="password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Required for BW TX300v3. Leave blank when editing to preserve the saved password.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="transmitterconfig",
            name="transmitter_type",
            field=models.CharField(
                choices=[
                    ("none", "None / disabled"),
                    ("cobalt_c300", "Aquabroadcast COBALT C300"),
                    ("bw_tx300v3", "BW Broadcast TX300v3"),
                ],
                default="cobalt_c300",
                help_text="Select the transmitter protocol, or disable transmitter monitoring.",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="monitorcheck",
            name="transmitter_indicator",
            field=models.CharField(
                blank=True,
                help_text="Transmitter status/check identifier. Existing COBALT names are translated by compatible vendor drivers where supported.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="monitorcheck",
            name="transmitter_parameter",
            field=models.CharField(
                blank=True,
                help_text="Transmitter parameter/check identifier. Existing COBALT names are translated by compatible vendor drivers where supported.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="transmitterconfig",
            name="host",
            field=models.CharField(
                blank=True,
                help_text="Transmitter IP address or hostname.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="transmitterconfig",
            name="port",
            field=models.PositiveIntegerField(
                default=23,
                help_text="TCP port for the selected transmitter's monitoring protocol.",
            ),
        ),
        migrations.AlterField(
            model_name="transmitterconfig",
            name="timeout_seconds",
            field=models.FloatField(
                default=3.0,
                help_text="Maximum seconds for each bounded connection or protocol wait.",
            ),
        ),
    ]
