# Generated by Django 5.2.15 on 2026-09-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_transmitter_vendor_and_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorcheck',
            name='kind',
            field=models.CharField(choices=[('systemd', 'Systemd Service'), ('disk', 'Disk Usage'), ('cpu', 'CPU Usage'), ('memory', 'Memory Usage'), ('temperature', 'Temperature'), ('transmitter_param', 'Transmitter Parameter'), ('transmitter_indicator', 'Transmitter Status Indicator'), ('audio_silence', 'Audio Silence (Liquidsoap)'), ('encoder_group', 'Encoder Stream Health'), ('rbds', 'RBDS Connection'), ('weather', 'Weather Health')], max_length=24),
        ),
    ]
