"""
Django settings for isadoraair project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Parsed BEFORE SECRET_KEY so we can require a real key in production.
DEBUG = config('DEBUG', default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
# In development (DEBUG=True) a hardcoded dev-only fallback keeps
# fresh checkouts runnable without editing .env first. In production
# (DEBUG=False) SECRET_KEY MUST come from the environment -- silently
# falling back to the shared dev key would let a broken .env boot
# a "working" server whose session cookies, password reset tokens,
# and CSRF tokens are all forgeable by anyone with a git clone.
_SECRET_KEY_DEV_FALLBACK = 'django-insecure-mgl(1gz6l^$j*(q+-8+9rp3n%2=7l0sr9$iu-lapa4^_!2%#&+'
SECRET_KEY = config('SECRET_KEY', default='') or (
    _SECRET_KEY_DEV_FALLBACK if DEBUG else ''
)
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY is required when DEBUG=False. Set it in .env "
        "(generate one with: "
        "python -c 'from django.core.management.utils import get_random_secret_key; "
        "print(get_random_secret_key())')."
    )

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,isadoraair',
    cast=lambda v: [h.strip() for h in v.split(',')],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'adminsortable2',
    'hardware',
    'library',
    'encoders',
    'monitoring',
    'rbds',
    'road_conditions',
    'weather',
    'ogremote',
    'webrequests',
    'aircheck',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'library.middleware.GroupBasedAccessMiddleware',
    'library.middleware.StationTimeActivateMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # Must come first — axes needs first crack at authenticate() to
    # enforce lockout before the real backend even checks the password.
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Lock on the (username, IP) pair together, not either alone: pure
# username lockout lets an attacker bypass the limit by rotating
# User-Agent/cookies (axes' own AXES_W006 warning), but pure IP lockout
# would risk locking out the real user right alongside any prober
# sharing this box's one household NAT'd IP.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

# nginx proxies to gunicorn over loopback (proxy_pass http://127.0.0.1:8000),
# so REMOTE_ADDR is always nginx's own address, not the real client -- axes
# needs django-ipware to pull the real IP from X-Forwarded-For instead (nginx
# already sets this, see /etc/nginx/sites-available/isadoraair). proxy_count=0
# (not 1) -- confirmed live: nginx's $proxy_add_x_forwarded_for only appends
# the IMMEDIATE client's IP, not nginx's own address, so the header is a
# single IP here, not a 2-entry chain. proxy_count=1 would (and did, in
# testing) incorrectly expect a second hop's IP already present and return
# None instead.
AXES_IPWARE_PROXY_COUNT = 0
AXES_IPWARE_META_PRECEDENCE_ORDER = ("HTTP_X_FORWARDED_FOR",)

# Django admin's bulk actions (e.g. "Delete selected") POST one
# _selected_action field per checked row -- the default cap of 1000 is a
# DoS guard meant for public-facing forms and real bug, confirmed live:
# selecting all 1542 tracks in a single category and choosing "Delete
# selected" raised TooManyFieldsSent -> a bare 400 with no explanation.
# This admin is login+axes-protected, single-operator, on a LAN -- raised
# generously above the whole library's size (~29k tracks) rather than
# just past today's largest category, so this doesn't recur for a bigger
# future bulk selection either.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

# Protects every view by default (LoginRequiredMiddleware, Django 5.1+) —
# Django's own login/admin-login views are already exempted internally
# (login_required=False on their view functions), so this doesn't create
# a redirect loop. Any future view that must stay public needs the
# @login_not_required decorator explicitly.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'library:dashboard'
LOGOUT_REDIRECT_URL = 'login'

ROOT_URLCONF = 'isadoraair.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'library.context_processors.ui_theme',
                'library.context_processors.nav_menu',
                'library.context_processors.access_flags',
                'library.context_processors.station_timezone',
            ],
        },
    },
]

WSGI_APPLICATION = 'isadoraair.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Royalty reports live OUTSIDE MEDIA_ROOT because they're operational
# data (station's own generated regulatory filings) and don't belong
# in the repo tree or the media/ URL space. Overridable via .env so
# a fresh box can put them somewhere else if needed. The directory
# must exist and be writable by the service user before the /reports/
# page is used; see README step 4.
REPORTS_ROOT = config('REPORTS_ROOT', default='/var/lib/isadoraair/reports')

LIBRARY_ROOT = config('LIBRARY_ROOT', default='/srv/isadoraair/music')
WAVEFORMS_DIR = config('WAVEFORMS_DIR', default='/srv/isadoraair/waveforms')

# Where the GW3000/Ecowitt weather receiver writes latest_weather.json,
# wind_history.json, and smoothed_wind.json -- read by the /wx/ views and
# the companion `weather-ingest` cron scripts. The two sides must agree.
WEATHER_DATA_DIR = config('WEATHER_DATA_DIR', default='/var/lib/isadoraair/weather')

# CD ripping configuration -- drive path, read offset, staging dir,
# AccurateRip strictness -- lives in the CDRipConfig singleton
# (admin: /admin/library/cdripconfig/) so replacing the drive doesn't
# need a redeploy. See library/models.py CDRipConfig for defaults.

# MusicBrainz asks callers of its API to identify themselves via a
# useragent contact string (see https://musicbrainz.org/doc/MusicBrainz_API/Rate_Limiting)
# so they can reach out if a client misbehaves. Set this to an email
# address the station operator actually reads.
MUSICBRAINZ_CONTACT = config('MUSICBRAINZ_CONTACT', default='')

# Station identity for NCE reports moved to library.models.StationInfo
# (admin: Config > Station Info) in migration 0062. No .env keys.

# Kansas DOT CARS API (road conditions/construction): no credential
# settings here. The live API's Swagger spec declares HTTP Basic on
# every endpoint, but anonymous access was verified working for every
# endpoint this project uses (2026-08-04 reconnaissance), and there's
# no concrete reason yet to expose unused settings for a "first
# version." road_conditions.api.CarsApiClient still accepts
# username/password directly (and is tested doing so) if a future
# round needs to wire real settings back in once KDOT requires auth.
# The admin-editable RoadConditionsConfiguration model holds the
# (non-secret) base URL, poll cadence, and filters.

# --- Audio analysis thresholds ---
ANALYSIS_SAMPLE_RATE = config('ANALYSIS_SAMPLE_RATE', default=4410, cast=int)
ANALYSIS_WINDOW_SECONDS = config('ANALYSIS_WINDOW_SECONDS', default=0.05, cast=float)
ANALYSIS_WAVEFORM_POINTS = config('ANALYSIS_WAVEFORM_POINTS', default=1000, cast=int)
NEXT_START_THRESHOLD_DB = config('NEXT_START_THRESHOLD_DB', default=-26.0, cast=float)
CUE_IN_THRESHOLD_DB = config('CUE_IN_THRESHOLD_DB', default=-45.0, cast=float)
CUE_IN_MIN_SECONDS = config('CUE_IN_MIN_SECONDS', default=0.1, cast=float)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://isadoraair,https://127.0.0.1',
    cast=lambda v: [o.strip() for o in v.split(',')],
)

# Standard Django deploy-checklist hardening (manage.py check --deploy),
# added when this went internet-facing via oakgroveradio.dyndns.org.
# nginx already redirects all HTTP -> HTTPS and terminates SSL, so these
# just add defense-in-depth on top of that rather than changing behavior.
# Deliberately NOT setting SECURE_HSTS_SECONDS — Django's own docs warn
# it needs care, and it interacts badly with the self-signed cert this
# box is keeping for now (a browser that caches HSTS for this host would
# refuse to let you click through the self-signed warning at all).
SECURE_SSL_REDIRECT = True
# The GW3000/Ecowitt weather gateway is IoT firmware that POSTs plain
# HTTP with no TLS support at all -- exempted from the redirect so its
# uploads reach the view instead of bouncing off a 301 it can't follow.
# nginx also needs its own matching exemption (see deploy notes) since
# the redirect above only fires for requests that already got past
# nginx's own unconditional :80 -> :443 redirect.
SECURE_REDIRECT_EXEMPT = [r'^wx/gw3000$']
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# --- Email (Monitoring alerts) ---
EMAIL_BACKEND = 'library.email_backend.LoggingSMTPBackend'
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='isadoraair@localhost')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
