"""
Django settings for isadoraair project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from decouple import config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-mgl(1gz6l^$j*(q+-8+9rp3n%2=7l0sr9$iu-lapa4^_!2%#&+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,isadoraair,192.168.1.125',
    cast=lambda v: [h.strip() for h in v.split(',')],
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'adminsortable2',
    'hardware',
    'library',
    'encoders',
    'monitoring',
    'rbds',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # Must come first — axes needs first crack at authenticate() to
    # enforce lockout before the real backend even checks the password.
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Lock on the (username, IP) pair together, not either alone: pure
# username lockout lets an attacker bypass the limit by rotating
# User-Agent/cookies (axes' own AXES_W006 warning), but pure IP lockout
# would risk locking out the real user right alongside any prober
# sharing this box's one household NAT'd IP.
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # hours
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

# Protects every view by default (LoginRequiredMiddleware, Django 5.1+) —
# Django's own login/admin-login views are already exempted internally
# (login_required=False on their view functions), so this doesn't create
# a redirect loop. Any future view that must stay public needs the
# @login_not_required decorator explicitly.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'library:dashboard'
LOGOUT_REDIRECT_URL = 'login'

ROOT_URLCONF = 'isadoraair.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'library.context_processors.ui_theme',
            ],
        },
    },
]

WSGI_APPLICATION = 'isadoraair.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

LIBRARY_ROOT = config('LIBRARY_ROOT', default='/srv/isadoraair/music')
WAVEFORMS_DIR = config('WAVEFORMS_DIR', default='/srv/isadoraair/waveforms')

# --- Audio analysis thresholds ---
ANALYSIS_SAMPLE_RATE = config('ANALYSIS_SAMPLE_RATE', default=4410, cast=int)
ANALYSIS_WINDOW_SECONDS = config('ANALYSIS_WINDOW_SECONDS', default=0.05, cast=float)
ANALYSIS_WAVEFORM_POINTS = config('ANALYSIS_WAVEFORM_POINTS', default=1000, cast=int)
NEXT_START_THRESHOLD_DB = config('NEXT_START_THRESHOLD_DB', default=-26.0, cast=float)
CUE_IN_THRESHOLD_DB = config('CUE_IN_THRESHOLD_DB', default=-45.0, cast=float)
CUE_IN_MIN_SECONDS = config('CUE_IN_MIN_SECONDS', default=0.1, cast=float)

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://isadoraair,https://192.168.1.125',
    cast=lambda v: [o.strip() for o in v.split(',')],
)

# Standard Django deploy-checklist hardening (manage.py check --deploy),
# added when this went internet-facing via oakgroveradio.dyndns.org.
# nginx already redirects all HTTP -> HTTPS and terminates SSL, so these
# just add defense-in-depth on top of that rather than changing behavior.
# Deliberately NOT setting SECURE_HSTS_SECONDS — Django's own docs warn
# it needs care, and it interacts badly with the self-signed cert this
# box is keeping for now (a browser that caches HSTS for this host would
# refuse to let you click through the self-signed warning at all).
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# --- Email (Monitoring alerts) ---
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='isadoraair@localhost')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
